```{r,warning=FALSE,message=FALSE}
rm(list=ls())

##################
set.seed(133)

#### General packages #####
require(reshape2)
require(scales)
require(grid)
require(dplyr)
require(parallel)
require(stringr)

### Packages for data analysis
require(eummd)
require(cramer)
require(extRemes)
require(texmex)
require(FactoMineR)

###Packages for graphics

require(utils)
require(ggside)
require(patchwork)
require(viridis)
require(ggplot2)
require(cowplot)
require(gridExtra)
require(ggpubr)
require(stringr)


### Packages for machine learning #####
require(e1071)
require(randomForest)
require(pROC)


```

```{r}
#Functions from univariate case. 
source("functions/fonctions_perfs_ML.R")
source("functions/fonctions.R")

### Generation functions
source("functions_MV/functions_consistency.R")
source("functions_MV/functions_simul_MV.R")
source("functions_MV/functions_estim_simul_gPareto.R")

```


```{r,warning=FALSE}
F_names<-ls()
nb_heartsCPU<-detectCores()-2
FSIZE<-20
COMMON_theme<-theme(axis.title = element_text(size=FSIZE),
                    strip.text=element_text(size=FSIZE),
                    legend.title = element_text(size=FSIZE),
                    legend.text=element_text(size=17),
                    axis.text=element_text(size=17))
# Defining clusters --------------------------------------------------
heartsCPU<-makeCluster(nb_heartsCPU)
clusterExport(heartsCPU,varlist=F_names)

# Import residuals --------------------------------------------------------
cols_<-c("data"="blue","simulations"="orange",
         "confidence_band"="darkblue",
         "CEVmodel"="red")
variable<-"Surge"
```


```{r}
# Choice of the risk function ---------------------------------------------

Name_riskF<-"max"
Approach<-"HTawn"
METHOD_ANGLE<-"GaussMixture"
Name_riskF2<-Name_riskF

if(Approach=="AD"){
  if(param==TRUE){
    opt_used<-paste0("_",MODEL_used)
  }else{
    opt_used<-paste0("_np")
  }
  
}else{
  opt_used<-Approach
}


```

```{r}
### Marginal transformation tool used
METHOD_MGtransf<-"_Mixt_transf_"

### Modeling used for the angular time series
METHOD_ANGLE<-"GaussMixture"
Name_riskF2<-Name_riskF
q<-(40)
W_chosen<-c(0.3,0.7)
if(Name_riskF=="sum"){
  Risk_f<-function(x){return(sum(x))}
  wFun<-weightFun_sum
  dwFun<-DweightFun_sum
  
}
if(Name_riskF=="max"){
  Risk_f<-function(x){return(max(x))}
}
if(Name_riskF=="sum_penalized"){
  Risk_f<-function(x){return(sum_penalized(x = x,vect_w = c(0.7,0.3)))}
  wFun<-function(x,u){
    weightFun_sum_penalized(x = x,u = u,
                            vect_w = W_chosen)
  }
  dwFun<-function(x,u){
    DweightFun_sum_penalized(x = x,u = u,
                             vect_w = W_chosen)
  }
}

if(Name_riskF=="Weighted_NQ"){
  Name_riskF2<-paste0(Name_riskF,"_q=",q)
  Risk_f<-function(x){
    return(Norm_q(x=x,q=q,
                  weights_nq = c(0.7,0.3)))
  }
  wFun<-function(x,u){
    return(weightFun_nq(x = x,u = u,
                        q = q,
                        weights_nq =c(0.7,0.3)))
  }
  dwFun<-function(x,u){
    return(DweightFun_nq(x = x,u = u,
                         q = q,weights_nq = c(0.7,0.3)))
  }
}
ANALYSIS_for_resid<-FALSE
L_nameV<-c("Surge","Hs","U")
```

```{r}
if(isTRUE(ANALYSIS_for_resid)){
  Prefix<-""
}else{
  Prefix<-"KNN_"
}
L_whole<-list()
D<-length(L_nameV)

Cplmt<-paste0(METHOD_MGtransf,"_d=",D)
Cplmt_for_sim<-paste0(METHOD_MGtransf,"_",
                      opt_used,"_d=",D)
```


```{r}
### Import of simulations-----------------
if(ANALYSIS_for_resid){
  l_root<-"residuals_MV/"
  path <- paste0(getwd(),"/residuals_MV/")
  ROOT_import<-paste0(path,Name_riskF2,"/")
  CPLMT<-"_resid"
  path_graph<-paste0(getwd(),"/Graphics_MV/resid")
 
}else{
  l_root<-"data_detrend_Winter/"
  path <- paste0(getwd(),"/Generated_extremes/")
  ROOT_import<-paste0(path,Name_riskF2,"/")
  CPLMT<-"_data"
  path_graph<-paste0(getwd(),"/Graphics_MV/data")
}

```

```{r,warning=FALSE,message=FALSE}
### New directories to export graphics--------------

## Create the new sub directory if needed
try({
  dir.create(file.path(path_graph))
})
## Create for the specific risk function used the sub directory used.
newfolder <- Name_riskF2
try({
  dir.create(file.path(path_graph, newfolder))
})
Updated<-paste0(path_graph,"/",Name_riskF2)
ROOT_export_graph<-paste0(path_graph,"/",
                          Name_riskF2,"/")
try({
  Corr_path<-paste0(ROOT_export_graph,"Corr")
  dir.create(file.path(Corr_path))
  TREND_path<-paste0(ROOT_export_graph,"Trend")
  dir.create(file.path(TREND_path))
  Theta_path<-paste0(ROOT_export_graph,"Theta")
  dir.create(file.path(Theta_path))
  Lg_path<-paste0(ROOT_export_graph,"RisKfunctions")
  dir.create(file.path(Lg_path))
  PCA_path<-paste0(ROOT_export_graph,"PCA")
  dir.create(file.path(PCA_path))
  Extremo_path<-paste0(ROOT_export_graph,"extremes")
  dir.create(file.path(Extremo_path))
  ML_path<-paste0(ROOT_export_graph,"ML")
  dir.create(file.path(ML_path))
  for(name_V in L_nameV){
    newfolder<-name_V
    try({
      dir.create(file.path(TREND_path, newfolder))
      dir.create(file.path(Theta_path, newfolder))
      dir.create(file.path(PCA_path, newfolder))
      dir.create(file.path(Extremo_path, newfolder))
    })
  }
})
```


```{r}
USE_log<-FALSE
if(USE_log){
  CPLMT_graph_theta<-"With_log"
}else{
  CPLMT_graph_theta<-"RAW"
}
path <- paste0(getwd(),"/residuals_MV")
newfolder <- "Conversion"
path_conversion<-paste0(path,"/")
if(isTRUE(ANALYSIS_for_resid)){
  Prefix<-""
}else{
  Prefix<-"KNN_"
}
L_whole<-list()
```


```{r}
D<-length(L_nameV)

Cplmt<-paste0(METHOD_MGtransf,"_d=",D)
Cplmt_for_sim<-paste0(METHOD_MGtransf,"_",
                      opt_used,"_d=",D)

if(ANALYSIS_for_resid){
  
  Cplmt_filenameSim_import<-paste0("_simul_",Cplmt_for_sim,".csv")
  Cplmt_filenameObs_import<-paste0("_obs_ext_",Cplmt,".csv")
  Simuls<-read.csv(file=paste0(ROOT_import,variable,
                               Cplmt_filenameSim_import))
  Reals<-read.csv(file=paste0(ROOT_import,variable,
                              Cplmt_filenameObs_import))
  for(nameCol in L_nameV){
    if(METHOD_MGtransf=="_Mixt_transf_"){
      Reals_whole<-read.csv(file = paste0(path,"/",
                    nameCol,
                    "_residuals_",D,".csv"))
    }else{
      Reals_whole<-read.csv(file =paste0(path_conversion,
                     newfolder,"/",nameCol,
                      "_data_ref_",D,".csv"))
    }
    colnames(Reals_whole)<-substr(colnames(Reals_whole),
                                  start = 2,stop = 3)
    L_whole[[nameCol]]<-Reals_whole
    
  }
  
}else{
  Cplmt_filenameSim_import<-paste0("_fsim_",Cplmt_for_sim,".csv")
  Cplmt_filenameObs_import<-paste0("_fdata_",Cplmt,".csv")
  Simuls<-read.csv(file=paste0(ROOT_import,Prefix,variable,
                               Cplmt_filenameSim_import))
  Reals<-read.csv(file=paste0(ROOT_import,variable,
                              Cplmt_filenameObs_import))
  for(nameCol in L_nameV){
    if(nameCol=="U"){
      Reals_whole<-read.csv(paste0(l_root,nameCol,
                                   "_trunc_detrend.csv"))
    }else{
      Reals_whole<-read.csv(paste0(l_root,nameCol,
                                 "_detrend.csv"))
    }
    Number_measures<-ncol(Reals_whole)
    Reals_whole<-Reals_whole[,c(2:Number_measures)]
    colnames(Reals_whole)<-substr(colnames(Reals_whole),
                                  start = 2,stop = 3)
    L_whole[[nameCol]]<-Reals_whole
  }
}

```

```{r}
# PCA coordinates ---------------------------------------------------------
if(ANALYSIS_for_resid){
  N_sum<-0
  Rank_Cop<-1
  LIST_GG<-list()
  Fich_1<-read.csv(file = paste0(ROOT_import,Prefix,"_coord_data.csv"))
  Fich_2<-read.csv(file = paste0(ROOT_import,Prefix,"_coord_simul.csv"))
  Fich_1<-Fich_1[,c(2:ncol(Fich_1))]
  Fich_2<-Fich_2[,c(2:ncol(Fich_2))]
  colnames(Fich_1)<-c(1:ncol(Fich_1))
  colnames(Fich_2)<-colnames(Fich_1)
  Theta_obs<-t(t(Fich_1))
  Theta_sim<-t(t(Fich_2))
  
  # MV test PCA coords ----------------
  #################

  Parwise_combined<-t(utils::combn(x = c(1:ncol(Fich_1)),m = 2))
  for(j in c(1:nrow(Parwise_combined))){
    index_i<-Parwise_combined[j,1]
    index_j<-Parwise_combined[j,2]
    Pair_<-c(index_i,index_j)
    df_combo<-rbind.data.frame(Fich_1[,Pair_],
                               Fich_2[,Pair_])
    colnames(df_combo)<-c("V1","V2")
    df_combo$Legend<-c(rep("data",nrow(Fich_1)),
                       rep("simulations",nrow(Fich_2)))
    Lab_i<-expression("C"[index_i])
    Lab_i_eval<-do.call("substitute", list( Lab_i[[1]], 
            list(index_i =index_i)))
    Lab_j<-expression("C"[index_j])
    Lab_j_eval<-do.call("substitute", list( Lab_j[[1]], 
                                            list(index_j =index_j)))
    GG1<-ggplot2::ggplot(data=df_combo,aes(x=V1,y=V2,
                      colour=Legend,shape=Legend),
    )+
      geom_point(aes(size=Legend))+
      geom_xsidedensity(data=df_combo,aes(fill=Legend), alpha = 0.5)+
      geom_ysidedensity(data=df_combo,aes(fill=Legend), alpha = 0.5)+
      xlab(Lab_i_eval)+ylab(Lab_j_eval)+scale_color_manual(values=cols_)+
      scale_fill_manual(values=cols_)+
      scale_shape_manual(values = c("simulations"=17,"data"=19))+
      scale_size_manual(values=c("simulations"=0.75,"data"=1.5))+
      guides(fill="none")+
      theme(axis.title=element_text(size=15),
            legend.text=element_text(size=10))
    LIST_GG[[j]]<-GG1
    N_sum<-N_sum+1
    if(N_sum==3){
      #blank <- ggplot2::ggplot(width=0.5) + theme_void()
      obj1<-LIST_GG[[3*(Rank_Cop-1)+1]] 
      obj2<-LIST_GG[[3*(Rank_Cop-1)+2]]
      obj3<-LIST_GG[[3*(Rank_Cop)]]
      top_row<-(obj1+obj2)
      Second_row<-plot_spacer() + obj3 + plot_spacer()+
        plot_layout(widths = c(0.5, 1,0.5))
      All_PCA_coords<-top_row/Second_row
      Name_graph<-paste0("/",Prefix,
                      "_Copula_model_vs_coords_",Rank_Cop,".png")
      ggsave(filename =paste0(Theta_path,Name_graph),
             plot =All_PCA_coords,width = 12,height = 9)
      Rank_Cop<-Rank_Cop+1
      N_sum<-0
    }
  }
}
```

```{r}
# Plots with more than 1 forcing condition --------------------------------
##########
Link_RF<-paste0("residuals_MV/",Name_riskF2,"/")
Unit_variable<-list("Surge"="(m)","U"="(m/s)",
                    "Hs"="(m)")
list_simul<-list()
list_obs<-list()
Nshown<-50
Obs_taken<-sample(c(1:nrow(Reals)),size = Nshown,
                  replace = FALSE)
Simul_taken<-sample(c(1:nrow(Simuls)),size = Nshown,
                    replace = FALSE)
```

```{r}
# Params for extremo computation-----------------

q_chosen<-0.70

Times_chosen<-c(19,13,25,31)
periods_years<-c(2,5,10,20,50,80,
                 100,120,200,400)
NB_years<-37
Qtile_per_year<-0.90
D<-length(L_nameV)
l_exs_simuls<-list()
l_PCA<-l_exs_simuls

common_scale <- scale_color_manual(values = cols_)

common_guides <- guides(color = guide_legend(title = "Legend"))
common_linetype<-scale_linetype_manual("Legend",
              values=c("confidence_band"=2,
                      "mean"=5))
Time_label<-"Time (hour) with respect to tidal peak"
```


```{r}
### List for future graphics
##################
J<-1

L_L2_simul<-list()
L_L2_obs<-list()
L_var_name_sim<-list()
L_var_name_data<-L_var_name_sim
L_result_mmd<-list()
Times_available_graphics<-list()
ROOT_inds_exts<-paste0("residuals_MV/",Name_riskF2,"/")

for(NV in L_nameV){
  
  Z<-which(L_nameV==NV)
  Simuls_1<-read.csv(file=paste0(ROOT_import,Prefix,NV,
                    Cplmt_filenameSim_import))
  Reals_1<-read.csv(file=paste0(ROOT_import,NV,
                    Cplmt_filenameObs_import))
  colnames(Simuls_1)<-substr(colnames(Simuls_1),
                           start=2,stop=3)
  colnames(Reals_1)<-colnames(Simuls_1)
  #########################
  
  Times_available_graphics[[NV]]<-colnames(Reals_1)

  ### Fill list for future ML
  L_L2_simul[[NV]]<-apply(X = Simuls_1,
          MARGIN = 1,FUN = calcul_norm_L2)
  L_L2_obs[[NV]]<-apply(X = Reals_1,
          MARGIN = 1,FUN = calcul_norm_L2)

  list_simul[[NV]]<-Simuls_1
  list_obs[[NV]]<-Reals_1
  ### Fill rep. of variable names for graphical outputs.
  L_var_name_data[[NV]]<-rep(NV,
                            nrow(Reals_1))
  L_var_name_sim[[NV]]<-rep(NV,
                            nrow(Simuls_1))
  ######
  Matrix_couples_varj<-list()
  L<-ncol(Reals_1)
  z<-1
  vecteur_distances<-c()
  for(j in 1:L){
    #condition imposée sur le deuxième Time.
    valeurs_t_plus_h<-j:L
    for (i in valeurs_t_plus_h){
      Matrix_couples_varj[[z]]<-c(i,j)
      vecteur_distances<-c(vecteur_distances,abs(i-j))
      z<-z+1
    }
  }

  # Violin plots/Boxplots ------------------------------------------------------------
  ##########
  Melt_sim_violin<-melt(t(Simuls_1))
  Melt_data_violin<-melt(t(Reals_1))
  colnames(Melt_sim_violin)<-c("time","id","value")
  colnames(Melt_data_violin)<-c("time","id","value")
  Melt_whole<-rbind.data.frame(Melt_data_violin,
                               Melt_sim_violin)
  Melt_whole$origin<-c(rep("data",nrow(Melt_data_violin)),
                       rep("simulations",nrow(Melt_sim_violin)))
  Melt_whole$time<-as.character(( Melt_whole$time-19)/6)
  GG_violin<-ggplot2::ggplot(data=Melt_whole,aes(x = time,y=value))+
    geom_boxplot(width=0.8,aes(fill=origin))+
    facet_wrap(~origin)+
    labs(fill="Legend")+
    ylab(paste0("value ",Unit_variable[[NV]]))+
    theme(axis.text.x = element_blank())+
    scale_fill_manual(values=cols_)
  ggsave(filename = 
        paste0(TREND_path,"/",NV,"/",Prefix,NV,
            "_boxplot_sim_obs",CPLMT,"_d=",D,
            ".png"),
         plot = GG_violin,
         width = 8,height = 6)
  # Quantile evolution -----------------------------------------------------------------
  #####
  # Simul -------------------------------------------------------------------
  estimator_95_simul<-apply(Simuls_1,MARGIN =2,
                            function(x){
                            return(as.numeric(quantile(x,0.95)))})
  estimator_025_simul<-apply(Simuls_1,MARGIN =2,
                            function(x){
                              return(as.numeric(quantile(x,0.025)))})
  estimator_05_simul<-apply(Simuls_1,MARGIN =2,
                            function(x){
                            return(as.numeric(quantile(x,0.05)))})
  estimator_50_simul<-apply(Simuls_1,MARGIN =2,
                            function(x){
                            return(as.numeric(quantile(x,0.50)))})
  estimator_975_simul<-apply(Simuls_1,MARGIN =2,
                             function(x){
                              return(as.numeric(quantile(x,0.975)))})
  
  ### Data ------------------
  ###############
  estimator_025<-apply(Reals_1,MARGIN =2,
                      function(x){
                        return(as.numeric(quantile(x,0.025)))})
  estimator_05<-apply(Reals_1,MARGIN =2,
                      function(x){
                      return(as.numeric(quantile(x,0.05)))})
  estimator_95<-apply(Reals_1,MARGIN =2,
                      function(x){
                      return(as.numeric(quantile(x,0.95)))})
  estimator_975<-apply(Reals_1,MARGIN =2,
                       function(x){
                      return(as.numeric(quantile(x,0.975)))})
  estimator_50<-apply(Reals_1,MARGIN =2,
                      function(x){
                      return(as.numeric(quantile(x,0.50)))})
  ### Export exs of sims/vs data
  mu1<-apply(X = Simuls_1,MARGIN = 2,FUN = mean)
  mu2<-apply(X = Reals_1,MARGIN = 2,FUN = mean)
  NB_sample<-sample(c(1:nrow(Simuls_1)),
                    size = Nshown,replace = FALSE)
  NB_sample_data<-sample(c(1:nrow(Reals_1)),
                    size = Nshown,replace = FALSE)
  Melteur<-melt(t(Simuls_1[NB_sample,]))
  colnames(Melteur)<-c("Time","Index","valeur")
  Melteur$Index<-as.character(Melteur$Index)
  
  M2<-melt(t(Reals_1[NB_sample_data,]))
  colnames(M2)<-c("Time","Index","valeur")
  M2$Index<-as.character(M2$Index)
  Timenorm<-M2$Time-min(unlist(M2$Time))+1
  M2$bound_inf<-estimator_025[Timenorm]
  M2$bound_sup<-estimator_975[Timenorm]
  
  Timenorm_sim<-Melteur$Time-min(unlist(Melteur$Time)
                                 )+1
  Melteur$bound_inf<-estimator_025_simul[Timenorm_sim]
  Melteur$bound_sup<-estimator_975_simul[Timenorm_sim]
  
  min_y<-min(min(M2$valeur),min(Melteur$valeur))
  max_y<-max(max(M2$valeur),max(Melteur$valeur))
  
  M2$mu<-mu2[Timenorm]
  Melteur$mu<-mu1[Timenorm_sim]
  M2$Time<-(M2$Time-19)/6
  Melteur$Time<-(Melteur$Time-19)/6
  Nv_correct<-Fct_correct_name(x =NV,target = "Surcote",
                               replacement = "Surge")
  yleft <- paste0(Nv_correct," ",
                  Unit_variable[[NV]])
  Whole<-rbind.data.frame(Melteur,M2)
  Whole$origin<-c(rep("simulations",nrow(Melteur)),
                  rep("data",nrow(M2)))
  Whole$Index <- as.factor(Whole$Index)
  GGsum<-ggplot2::ggplot(data=Whole,
                aes(x=Time,y=valeur,col=Index,
                    group=Index,
                ))+
    geom_ribbon(aes(ymin=bound_inf,ymax=bound_sup,
                    linetype="confidence_band",
                    group=1),
                alpha=0.15,fill="grey",
                col="darkblue")+
    geom_line(aes(x = Time,y=mu,linetype="mean"),
              col="red",size=1.1)+
    guides(col="none")+
    facet_wrap(~origin,nrow=2)+
    
    geom_line(alpha=0.7)+
    xlab(Time_label)+
    ylab(yleft)+common_linetype+
    labs(linetype="Legend")+
    COMMON_theme+theme(legend.direction = "horizontal")
  # Obs-confidence -----------------------------------------------------------
  N_rep<-500
  B<-nrow(Reals_1)
  lq<-c(0.05,0.50,0.95,0.975)
  Trend<-replicate(N_rep,Resamples_trends(B = B,extremes_indus= Reals_1,
                        list_Q =lq))
  
  bound_minus05<-apply(Trend[1,,],MARGIN = 1,
                       FUN = function(x){return(quantile(x,0.025))})
  bound_plus05<-apply(Trend[1,,],MARGIN = 1,
                      FUN = function(x){return(quantile(x,0.975))})
  
  ##########
  bound_minus50<-apply(Trend[2,,],MARGIN = 1,
                       FUN = function(x){return(quantile(x,0.025))})
  bound_plus50<-apply(Trend[2,,],MARGIN = 1,
                      FUN = function(x){return(quantile(x,0.975))})
  
  ########
  bound_minus95<-apply(Trend[3,,],MARGIN = 1,
                       FUN = function(x){return(quantile(x,0.025))})
  bound_plus95<-apply(Trend[3,,],MARGIN = 1,
                      FUN = function(x){return(quantile(x,0.975))})
  
  ######
  bound_minus975<-apply(Trend[4,,],MARGIN = 1,
                        FUN = function(x){return(quantile(x,0.025))})
  bound_plus975<-apply(Trend[4,,],MARGIN = 1,
                       FUN = function(x){return(quantile(x,0.975))})
  
  # Graphics ----------------------------------------------------------------
  df<-cbind.data.frame(c(estimator_05,estimator_50,
                         estimator_95,estimator_975),
                       c(bound_minus05,bound_minus50,
                         bound_minus95,bound_minus975),
                       c(bound_plus05,bound_plus50,
                         bound_plus95,bound_plus975))
  colnames(df)<-c("estimator","bound_minus","bound_plus")
  
  df$estimator_simul<-c(estimator_05_simul,estimator_50_simul
                        ,estimator_95_simul,estimator_975_simul)
  df$Time<-rep(as.numeric(colnames(Reals_1)),
               4)
  df$Time<-(df$Time-19)/6
  df$percent<-c(rep("Q05",ncol(Reals_1)),
                rep("Q50",ncol(Reals_1)),
                rep("Q95",ncol(Reals_1)), 
                rep("Q975",ncol(Reals_1)))
  GG_percent<-ggplot2::ggplot(data=df,aes(x=Time,y=estimator,
                  group=interaction(percent),col="data"))+
    facet_wrap(~percent,scales="free_y")+
    geom_line()+
    geom_point()+
    geom_ribbon(
      mapping = aes(ymin=bound_minus,
                ymax=bound_plus,col="confidence_band"),
                alpha=0.15,
                fill="grey", linetype = "dashed")+
    geom_line(aes(x=Time,y=estimator_simul,col="simulations"),
              linetype=2)+
    COMMON_theme+theme(
          legend.position="bottom",
          legend.direction="horizontal")+
    ylab(paste0("value ",Unit_variable[[NV]]))+
    scale_color_manual(values=cols_)+
    xlab(Time_label)+
    labs(col="Legend")
  ggsave(filename = paste0(TREND_path,"/",NV,"/QQ_evol_",
                           Prefix,NV,CPLMT,
                           opt_used,"_d=",D,".png"),
         plot = GG_percent,width = 10,height = 5)
  # Plots  ------------------------------------------------------------------
  ###########
  Q975<-apply(X = Reals_1,
              MARGIN =2,FUN = function(x){
                return(quantile(x,0.975))
              })
  Q025<-apply(X = Reals_1,
              MARGIN = 2,FUN=function(x){
                return(quantile(x,0.025))
              })
  Q975_sim<-apply(X = Simuls_1,
              MARGIN = 2,FUN=function(x){
                return(quantile(x,0.975))
              })
  Q025_sim<-apply(X = Simuls_1,
              MARGIN =2,FUN= function(x){
                return(quantile(x,0.025))
              })
  Means_var<-colMeans(Reals_1)
  Means_var_sim<-colMeans(Simuls_1)
  Obs_shown<-Reals_1[Obs_taken,]
  Simul_shown<-Simuls_1[Simul_taken,]
  Melt_data<-melt(t(Obs_shown))
  colnames(Melt_data)<-c("time","id","value")
  Melt_data$mean<-Means_var[Melt_data$time]
  Melt_data$Qinf<-Q025[Melt_data$time]
  Melt_data$Qsup<-Q975[Melt_data$time]
  
  Melt_sim<-melt(t(Simul_shown))
  colnames(Melt_sim)<-c("time","id","value")

  Melt_sim$mean<-Means_var_sim[Melt_sim$time]
  Melt_sim$Qinf<-Q025_sim[Melt_sim$time]
  Melt_sim$Qsup<-Q975_sim[Melt_sim$time]
  Melt_all<-rbind.data.frame(
    Melt_data,Melt_sim
  )
  Melt_all$origin<-c(rep("data",nrow(Melt_data)),
                     rep("simulations",nrow(Melt_sim)))
  Melt_all$time<-(Melt_all$time-19)/6

  min_y<-min(min(Melt_all$Qinf),min(Melt_all$value))
  max_y<-max(max(Melt_all$Qsup),max(Melt_all$value))
  
  # Kendall correlation coefficient ---------------
  # -------------------------------
  fnct_quantile<-function(x,q){
    M<-apply(X = x,MARGIN = 2,FUN = function(X){return(as.numeric(quantile(X,q,
    )))})
    return(M)
  }
  type_corr<-"kendall"

  Coor_lien_real<-estim_corr_tidal_cycle(
            Matrix_couples =Matrix_couples_varj,
            functional_inds = Reals_1,
            type_corr = type_corr)
  Coor_lien_simul<-estim_corr_tidal_cycle(
            Matrix_couples = Matrix_couples_varj,
            functional_inds = Simuls_1,type_corr =type_corr)

  df_coor_lien<-cbind.data.frame(Coor_lien_real,Coor_lien_simul,
                                 vecteur_distances)
  colnames(df_coor_lien)<-c("value_data","value_simul",
                            "delta")
  resultat_corr<-df_coor_lien %>% group_by(delta) %>%summarise(
    val_data=mean(value_data),
    val_simul=mean(value_simul))
  
  B<-nrow(Reals_1)
  Result_resample_corr<-replicate(n = 500,
              expr = fnct_estim_corr_resample(inds_ext=Reals_1,
              type_corr="kendall",
            Matrix_couples=Matrix_couples_varj,
              vector_distances = vecteur_distances))
  Q05_coor<-fnct_quantile(x = t(Result_resample_corr),q=0.05)
  Q95_corr<-fnct_quantile(x = t(Result_resample_corr),q=0.95)
  resultat_corr$bound_inf<-Q05_coor
  resultat_corr$bound_sup<-Q95_corr
  GG_kendall<-ggplot2::ggplot(data=resultat_corr,aes(
              x=delta,y=val_simul,col="simulations"))+
    geom_point()+
    geom_point(aes(y=val_data,col="data"))+
    scale_color_manual(values = cols_)+
    ggtitle(paste0("Simul vs data for the correlation ", type_corr))+
    geom_ribbon(
      mapping =aes(ymin=bound_inf,
          ymax=bound_sup,col="confidence_band"),
                alpha=0.15,fill="grey", linetype = "dashed")+
    ylab("value")+xlab("Lag_h")
  
  ggsave(filename = paste0(Extremo_path,"/",NV,"/",
                           Prefix,NV,"_corr_kendall_univ",
                           CPLMT,opt_used,"_d=",D,".png"),
         plot = GG_kendall,
         width = 8,height = 6)
  # Return levels -------------------------
  ################
  LIST_GG_RL<-list()
  Bool_var<-sapply(as.character(Times_chosen),
                function(x){
                  return(x%in%colnames(Simuls_1))})
  Available<-which(Bool_var)
  Times_avai<-Times_chosen[Available]
  for(ind_t in c(1:length(Times_avai))){

    t<-as.character(Times_avai[ind_t])
    if(ANALYSIS_for_resid){
      link_data<-paste0(l_root,NV,"_residuals_",
                        D,".csv")
      Data_obs<-read.csv(file=link_data)
      colnames(Data_obs)<-substr(colnames(Data_obs),
                                 start = 2,stop = 3)
    }else{
      link_data<-paste0(l_root,NV,"_detrend.csv")
      Data_obs<-read.csv(file=link_data)[,2:38]
      colnames(Data_obs)<-c(1:37)
    }
    Indexes_exceed<-read.csv(file=paste0(ROOT_inds_exts,
                                         "ext_series_chosen_risks_",
                            length(L_nameV),".csv"))
    Indexes_exceed<-Indexes_exceed[,3]
    series_simul<-Simuls_1[,t]
    series_t<-Data_obs[,t]
    threshold<-quantile(series_t,Qtile_per_year)
    npy<-length(series_t)/NB_years
    series_ext<-subset(series_t,series_t>threshold)
    P_lim<-3*NB_years
    periods_years<-periods_years[which(periods_years<P_lim)]
    P<-1-(npy*periods_years)^(-1)
    Y_graph_lim<-c(0.80*threshold,max(max(series_simul),
                                      max(series_t))*1.20)
    GG_rel<-RL_ggplot_cond_ext(series = series_t,
         seuil = threshold,
         period_years = periods_years,
         NPY = npy,plus_simul = TRUE,
         series_simul = series_simul, 
         unit_used = Unit_variable[[NV]] , 
         nom_variable =NV,cols_ggplot = cols_, 
         ylim_opt = Y_graph_lim,alpha=0.05,
         Individus_exts=Indexes_exceed)$GG_plot
    
    LIST_GG_RL[[ind_t]]<-GG_rel
  }
  NB_divisions<-length(Times_avai)%/%2
  for(Z in c(1:NB_divisions)){
    Ind1<-(Z-1)*2+1
    Ind2<-Z*2
    GG_orig<-LIST_GG_RL[[Ind1]]
    LGD_RL<-plot_grid(ggpubr::get_legend(GG_orig))
    GG_time1<-GG_orig+
      guides(col="none")
    GG_time2<-LIST_GG_RL[[Ind2]]+
      guides(col="none")
    GG_time12<-GG_time1+
      GG_time2+
      plot_layout(axis_titles = "collect")
    
    
    Time1<-Times_avai[Ind1]
    Time2<-Times_avai[Ind2]
    Name_file<-paste0("rlevel_simul_vs_obs_",NV,"_",
                      Time1,"_",Time2,opt_used,"_",D,
                      ".png")
    final_plotRL<-plot_grid(GG_time12,LGD_RL,ncol=1,
                              rel_heights =c(10,1))
    f_RL_export<-ggdraw()+
      draw_plot(final_plotRL)+
      theme(plot.background = element_rect(fill = "white", 
                                           color = NA))
    Object_RL_twotimes<-f_RL_export
    ggsave(filename = paste0(Extremo_path,"/",
                             NV,"/",Prefix,
                             Name_file),
           plot = Object_RL_twotimes,width = 14,
           height = 7)
  }
  
  Z<-Z+1  
  # PCA coordinates ---------------------------------------------------------
  Nb_scores<-3

  ### Avoid division by 0
  L_simul<-apply(X = Simuls_1,MARGIN = 1,FUN = max)
  L_reality<-apply(X = Reals_1,MARGIN = 1,FUN = max)
  POS_sim<-which(L_simul>0)
  Angle_simul<-t(t(Simuls_1[POS_sim,])%*%diag((L_simul[POS_sim]+1)^(-1)))
  
  POS<-which(L_reality>0)
  Angle_inds<-t(t(Reals_1[POS,])%*%diag((L_reality[POS]+1)^(-1)))
  PCA_<-FactoMineR::PCA(X = Angle_inds,scale.unit = TRUE,
                        graph = FALSE)
  
  percent_variance<-PCA_$eig[c(1:Nb_scores),2]
  # Calculate mean and standard deviation -----------------------------------
  sd_<-apply(X =Angle_inds,MARGIN = 2,FUN = sd)
  mu_<-colMeans(Angle_inds)
  Angle_simul_std<-scale(Angle_simul,center = mu_,
                         scale = sd_)
  
  # Obtain the coordinates for each dimension -------------------------------
  coords_data<-PCA_$ind$coord[,c(1:Nb_scores)]
  V<-PCA_$svd$V[,c(1:Nb_scores)]
  coords_simul<-Angle_simul_std%*%V
  KS_PCA_coords_<-rep(NA,Nb_scores)
  ### Univ gof test
  for(g in c(1:Nb_scores)){
    KS_PCA_coords_[g]<-ks.test(coords_simul[,g],
                               coords_data[,g])$p.value
  }
  ### MV gof test
  MV_MMD_Laplace_PCA_coords<-eummd::mmd(X=coords_simul,Y=coords_data,
                                kernel = "Laplacian",
                                  pval = TRUE)$pval
  MV_MMD_Gauss_PCA_coords<<-eummd::mmd(X=coords_simul,Y=coords_data,
                              kernel = "Gaussian",
                                  pval = TRUE)$pval
  L_result_mmd[[NV]]<-data.frame("Laplacian"=MV_MMD_Laplace_PCA_coords,
                                 "Gauss"=MV_MMD_Gauss_PCA_coords)
  
  df_PCA_simul<-as.data.frame(coords_simul)
  summary(df_PCA_simul)
  colnames(df_PCA_simul)<-sapply(c(1:ncol(df_PCA_simul)), 
                                 function(x){return(paste0("Score_",x))})
  
  df_PCA_data<-as.data.frame(coords_data)
  colnames(df_PCA_data)<-sapply(c(1:ncol(df_PCA_data)), 
                                function(x){return(paste0("Score_",x))})
  df_combo<-rbind.data.frame(df_PCA_data,df_PCA_simul)
  df_combo$type<-c(rep("data",nrow(df_PCA_data)),
                   rep("simulations",nrow(df_PCA_simul)))
  Ymax<-max(max(unlist(df_PCA_data$Score_2)),
            max(unlist(df_PCA_simul$Score_2)))
 
  
  LIMS_data<-cbind(apply(X = df_PCA_data,MARGIN = 2,
                   FUN = min),
                   apply(X = df_PCA_data,MARGIN = 2,
                         FUN = max))
  LIMS_sim<-cbind(apply(X = df_PCA_simul,MARGIN = 2,
                         FUN = min),
                   apply(X = df_PCA_simul,MARGIN = 2,
                         FUN = max))
  Xmin<-min(min(df_PCA_data$Score_1),
            min(df_PCA_simul$Score_1))
  Xmax<-max(max(df_PCA_data$Score_1),
            max(df_PCA_simul$Score_1))
  Xmid<-mean(c(Xmin,Xmax))
  Df_for_annotate<-cbind.data.frame(Xmid,Ymax,
                                    Nv_correct)
  colnames(Df_for_annotate)<-c("xspec","yspec","label_spec")
  Ymin<-min(LIMS_data[2,1],LIMS_sim[2,1])
  Ymax<-max(LIMS_data[2,2],LIMS_sim[2,2])
  GG0<-ggplot2::ggplot(df_combo,aes(x=Score_1,
                          y=Score_2))+
    geom_text(
      data=Df_for_annotate,
      aes(x=xspec,y=yspec,label=label_spec),
      size=10)
  GG0<-GG0+
    geom_point(data=df_PCA_data,aes(x=Score_1,y=Score_2,
                                    col="data"))+
    geom_point(data=df_PCA_simul,aes(x=Score_1,y=Score_2,
                                     col="simulations"),
               pch=17,size=0.75)+
    geom_xsidedensity(data=df_combo,aes(fill=type), 
                      alpha = 0.5)+
    geom_ysidedensity(data=df_combo,aes(fill=type), 
                      alpha = 0.5)+
    #"First dimension (",
    xlab(paste0(round(percent_variance[1],1),
                "% of the variance"))+
    #"Second dimension ("
    ylab(paste0(round(percent_variance[2],1),
                "% of the variance"))+
    scale_fill_manual(values=cols_)+
    guides(fill="none")+
    COMMON_theme+theme(axis.title = element_text(size=15),
                       axis.text = element_text(size=10))+
    common_scale+common_guides
  GGsum2<-GGsum+
    theme(legend.position = 'none',
          legend.direction = "horizontal")
  if(J==1){
    Modified<-GG0+
         theme(legend.direction = "horizontal")
    LEGEND_whole<-get_legend(Modified)
    Cum_exs_simuls<-GGsum2
    LEGEND_exs<-get_legend(GGsum)
    
  }else{
    Cum_exs_simuls<-Cum_exs_simuls+
      GGsum2
  }
  l_PCA[[NV]]<-GG0+
    theme(legend.position = 'none',
          legend.direction = "horizontal")
  J<-J+1
}
par(mfrow=c(2,1))
L_result_mmd
DF_pca_mmd<-melt(L_result_mmd)
write.csv(x = DF_pca_mmd,
          file=paste0(PCA_path,"/PCA_",
          Prefix,"pval_MMD.csv"),
          row.names = FALSE)
```

```{r}
### Exs simuls ---------------
################

LGD_exs<-plot_grid(LEGEND_exs)
intermed_plot_EXS<-Cum_exs_simuls+
  plot_layout(axis_titles = "collect_x")
Cum_exs_simuls
final_plot_EXS<-plot_grid(intermed_plot_EXS,LGD_exs,ncol=1,
                          rel_heights =c(10,1))
f_EXS_export<-ggdraw()+
  draw_plot(final_plot_EXS)+
  theme(plot.background = element_rect(fill = "white", 
        color = NA))
ggsave(filename = paste0(ROOT_export_graph,"/",Prefix,
            "exs_simuls_",Approach,
            "_d=",length(L_nameV),".png"),
       plot = f_EXS_export,width=length(L_nameV)*4,
       height = 5)
```

```{r}
# PCA -----------------
#############
LGD<-plot_grid(LEGEND_whole)
Xlab<-textGrob("First dimension",
              gp=gpar(fontsize=FSIZE))
Ylab<-textGrob("Second dimension",
               gp=gpar(fontsize=FSIZE),
               rot = 90)
Gtest<-gridExtra::grid.arrange(grobs=l_PCA,ncol=3,
                               left=Ylab,
                              bottom=Xlab)
final_plot_PCA<-plot_grid(Gtest,LGD,ncol=1,
                      rel_heights = c(7,1))
final_plot_PCA
f_PCA_export<-ggdraw()+
  draw_plot(final_plot_PCA)+
  theme(plot.background = element_rect(fill = "white", color = NA))
ggsave(filename = paste0(PCA_path,"/PCA_coords_",Approach,"_",Prefix,
                         "_d=",length(L_nameV),".png"),
       plot = f_PCA_export,width=10,height = 5)
```


```{r}
# Cross-extremogram -------------------------------------------------------
###########
ALL_CE<-Cross_Extremo_MV_all(list_simul = list_simul,
                  list_reality = list_obs,
                  list_names_VAR = L_nameV,
                  q_per_time = q_chosen,
                  B = 500)
WHOLE<-do.call(rbind.data.frame,ALL_CE)
GG_cross_Gam<-ggplot2::ggplot(data=WHOLE,
       aes(x=time_d,y=val_data,col="data"))+
  geom_point()+
  geom_line()+
  facet_wrap(~category,
             scales = "free")+
  geom_point(aes(x=time_d,y=val_sim,
                 col="simulations"),pch=2)+
  geom_line(aes(x=time_d,y=val_sim,
            col="simulations"))+
  geom_ribbon(mapping = aes(ymin=Qinf,ymax=Qsup,
              col="confidence_band"),
              alpha=0.15,
              fill="grey", linetype = "dashed")+
  scale_color_manual(values = cols_)+
  xlab("Lag h")+ylab(expression(lambda[jk]~"value"))+
  labs(col="Legend")+
  COMMON_theme+theme(
        legend.position = "bottom")+
  scale_linetype_manual("Legend",
                        values=c("confidence_band"=2,
                                 "mean"=5))

```

```{r}
Name_cats_vars<-L_nameV[1]
for(j_rest in c(2:length(L_nameV))){
  Name_cats_vars<-paste(Name_cats_vars,
                  L_nameV[j_rest])
}
ggsave(filename = paste0(Extremo_path,"/",Prefix,"cross_extremo_",
                         Name_cats_vars,"_",opt_used,"_d=",D,".png"),
       plot = GG_cross_Gam,
       width=3*length(L_nameV),
       height=8)
```


```{r}
# Correlation values-----------------------------------------------------
###########

# Fbvplot with several values ---------------------------------------------
t<-19
s<-13
i_index<-1
name_i<-L_nameV[i_index]
j_index<-2
name_j<-L_nameV[j_index]
Prop<-0.90
Pair_for_bv<-cbind(L_whole[[name_i]][,t],
                   L_whole[[name_j]][,s]
)
Pair_simulated_points<-cbind(list_simul[[name_i]][,t],
                             list_simul[[name_j]][,s])

Qs<-apply(X = Pair_for_bv,MARGIN = 2,FUN =
            function(x){return(as.numeric(quantile(x,Prop)))})


NL2_simul<-sapply(X = list_simul,
       function(x){return(apply(x,MARGIN=1,
                                    FUN = calcul_norm_L2))})
NL2_obs<-sapply(X = list_obs,
                  function(x){return(apply(x,MARGIN=1,
                                           FUN = calcul_norm_L2))})
NL2_obs<-as.data.frame(NL2_obs)
NL2_simul<-as.data.frame(NL2_simul)
colnames(NL2_obs)<-L_nameV
colnames(NL2_simul)<-colnames(NL2_obs)
NL2_obs<-as.data.frame(NL2_obs)
Risk_f_obs1<-apply(X = NL2_obs,MARGIN = 1,FUN = Risk_f)
Risk_f_obs<-cbind.data.frame(Risk_f_obs1,rep("data",
                                             length(Risk_f_obs1)))

NL2_simul<-as.data.frame(NL2_simul)
Sub_simul<-colnames(NL2_obs)

Risk_f_simul1<-apply(X = NL2_simul,MARGIN = 1,FUN = Risk_f)
```

```{r}
# Violin plots for each dataset (simulations and observations) ------------------------------------------
#####
Orig_s<-rep("simulations",length(Risk_f_simul1))
Risk_f_simul<-cbind.data.frame(Risk_f_simul1,Orig_s)
colnames(Risk_f_simul)<-c("Risk_f","orig")
colnames(Risk_f_obs)<-colnames(Risk_f_simul)
Risk_f_obs_simul<-rbind.data.frame(Risk_f_obs,Risk_f_simul)
colnames(Risk_f_obs_simul)<-c("value_Risk_f","origin")
GG_violin_Risk_f<-ggplot2::ggplot(data=Risk_f_obs_simul,
                         aes(x=origin,y=value_Risk_f,
                              fill=origin))+
  geom_violin()+
  geom_boxplot(width=0.3)+
  scale_fill_manual(values=cols_)+
  labs(fill="Legend")+ylab("value (m)")

ggsave(plot=GG_violin_Risk_f,
       filename=paste0(Lg_path,"/Violin_RiskF_data_sim_",Prefix,
                      CPLMT,"_d=",D,".png"),
       width=8,height=8)
```


```{r}
NL2_obs$origin<-rep("data",nrow(NL2_obs))
NL2_simul$origin<-rep("simulations",
                      nrow(NL2_simul))
NL2_all<-rbind.data.frame(NL2_obs,NL2_simul)
NL2_all<-melt(NL2_all)
colnames(NL2_all)<-c("origin","variable",
                     "value")
GG_violin<-ggplot2::ggplot(data=NL2_all,aes(x=origin,y=value,fill=origin))+
  facet_wrap(~variable,scales = "free")+
  geom_violin(alpha=0.6)+
  scale_fill_manual(values=cols_)+
  geom_boxplot(width=0.3)+
  labs(fill="Legend")+
  xlab("origin")+ylab("value (m)")

ggsave(plot=GG_violin,
       filename =paste0(Lg_path,
        "/Violin_RiskF_data_sim_varwise_",
      Prefix,CPLMT,"_d=",D,".png"),
       width=8,height=8)
```

```{r}
# MV gof test -----------------
#########
DF_L2_simul<-as.data.frame(L_L2_simul)
DF_L2_obs<-as.data.frame(L_L2_obs)

### MMD test ----------------
require(eummd)
require(cramer)

Data_RiskfF<-t(t(DF_L2_obs))
Sim_RiskfF<-t(t(DF_L2_simul))
cor.test(Data_RiskfF[,1],Data_RiskfF[,2]
         ,method="kendall")
cor.test(Sim_RiskfF[,1],Sim_RiskfF[,2]
         ,method="kendall")

MV_MMD_Laplace_RF<-eummd::mmd(
  X=Data_RiskfF,Y=Sim_RiskfF,
   kernel = "Laplacian",pval = TRUE)$pval

MV_MMD_Gauss_RF<-eummd::mmd(
  X =Data_RiskfF,Y=Sim_RiskfF,
     kernel = "Gaussian",pval = TRUE)$pval
MV_mmd_median_RF<-eummd::meammd(
  X =Data_RiskfF,Y=Sim_RiskfF,
      pval = TRUE)$pval
MV_Cramer_RF<-cramer::cramer.test(Data_RiskfF,Sim_RiskfF)$p.value
print("MV MMD test on RiskF")
print(c(MV_MMD_Laplace_RF,MV_MMD_Gauss_RF,MV_mmd_median_RF))

print("Cramer test on RiskF")
print(MV_Cramer_RF)
```

```{r}
####### Plot simulations------------
########################

Whole_L2<-rbind.data.frame(DF_L2_simul,DF_L2_obs)
Whole_L2$Legend<-c(rep("simulations",nrow(DF_L2_simul)),
                   rep("data",nrow(DF_L2_obs)))
if(D>2){
  Combn_rf<-t(utils::combn(c(1:D),m = 2))
}else{
  Combn_rf<-matrix(c(1,2),nrow = 1,ncol = 2,byrow = TRUE)
}
INTERSECTION_cols<-intersect(names(DF_L2_simul),names(DF_L2_obs))


```
```{r}

for(Z in c(1:nrow(Combn_rf))){
  Sub_comb<-Combn_rf[Z,]
  name_i<-L_nameV[Sub_comb[1]]
  name_j<-L_nameV[Sub_comb[2]]
  Sub_whole_j<-Whole_L2[,c(name_i,name_j,
                           "Legend")]
  colnames(Sub_whole_j)<-c("V1","V2","Legend")
  name_jcorrect<-Fct_correct_name(x = name_j,
                                  target = "Surcote",
                                  replacement = "Surge")
  name_icorrect<-Fct_correct_name(x = name_i,
                                  target = "Surcote",
                                  replacement = "Surge")
  GG_RF_j<-ggplot2::ggplot(data=Sub_whole_j,
                  mapping = aes(x=V1,y=V2,
                                colour=Legend,shape=Legend))+
    geom_point(aes(size=Legend))+
    geom_xsidedensity(data=Sub_whole_j,
                      aes(fill=Legend), alpha = 0.5)+
    geom_ysidedensity(data=Sub_whole_j,
                      aes(fill=Legend), alpha = 0.5)+
    scale_color_manual(values=cols_)+
    scale_fill_manual(values=cols_)+
    scale_shape_manual(values = 
                         c("simulations"=17,"data"=19))+
    scale_size_manual(values=
                        c("simulations"=0.75,"data"=1.5))+
    guides(fill="none")+
    xlab(paste(name_icorrect,
               Unit_variable[[name_i]]))+
    ylab(paste(name_jcorrect,
               Unit_variable[[name_j]]))+
    COMMON_theme+theme(
          legend.direction = "horizontal")
  if(Z==1){
    LG_ref<-get_legend(GG_RF_j)
    All_RISKF<-GG_RF_j+
      theme(legend.position = 'none')
  }else{
    All_RISKF<-All_RISKF+
      GG_RF_j+
      theme(legend.position = 'none')
  }
}
```


```{r}
### Export distribution of Risk function --------------
final_plot_RF<-plot_grid(All_RISKF,LG_ref,ncol=1,
          rel_heights = c(7,1))
f_RF_export<-ggdraw()+
  draw_plot(final_plot_RF)+
  theme(plot.background = element_rect(fill = "white", color = NA))
f_RF_export
ggsave(filename = paste0(Lg_path,"/Distrib_RiskF_d=",length(L_nameV),
                  "_",Approach,".png"),
       plot = f_RF_export,width=10,height = 6)
```


```{r}
#### Choose times + vars to analyse
VFIRST<-c(13,19)
VSECOND<-c(13,25)
VTHIRD<-c(25,31)
VFOURTH<-c(19,1)
VFIFTH<-c(19,19)
VSIXTH<-c(13,19)
Associate_vars<-function(vect_times,var_1,var2){
  l<-as.list(vect_times)
  names(l)<-c(var_1,var2)
  return(l)
}
VARFIRST<-L_nameV[c(1,3)]
VARSECOND<-L_nameV[c(3,2)]
VARTHIRD<-L_nameV[c(3,1)]
VARFOURTH<-L_nameV[c(3,1)]
VARFIFTH<-L_nameV[c(1,2)]
VARSIXTH<-L_nameV[c(1,2)]

MAT_times<-rbind(VFIRST,VSECOND,VTHIRD)
MAT_VAR<-rbind(VARFIRST,VARSECOND,
            VARTHIRD)

list_summary<-list()
for(i in c(1:nrow(MAT_times))){
  TIMES<-as.list(MAT_times[i,])
  names(TIMES)<-MAT_VAR[i,]
  list_summary[[i]]<-TIMES
}

```

```{r}
NPY<-5
NB_years<-c(20,50)
Levels_for_RL<-(NPY*(NB_years))^(-1)

### Export the required packages for the CPU ----------
list_EVALQ<-clusterEvalQ(heartsCPU, c(library(dplyr),library(reshape2),
                       library(ggplot2),
                       library(ggside),library(texmex),
                       library(stringr)))
```


```{r}
L_info_export<-list("model"=opt_used,
                    "prefix"=Prefix,
                    "complement"=CPLMT)
RUN_biv_analysis<-FALSE
if(RUN_biv_analysis){
  Summary_pairs<-parallel::parLapply(cl = heartsCPU,
      list_summary,F_automatic_ggplot_marg,
      Path_EXT = Extremo_path,Path_TREND = TREND_path,
      l_unit=Unit_variable,risk_function=Risk_f,
      ind_var_cond=2,levels_used=Levels_for_RL,
      L_obs=list_obs,L_simul=list_simul,
      L_whole_obs=L_whole,cols=cols_,
      hearts=heartsCPU,basis_functionGAM="tp",
      n_sim=1000,list_info_export=L_info_export,
      theme_common=COMMON_theme)
}


```


```{r}
# Consistency analysis with machine learning -----------------------------------------------------
##########
H_Params<-c("radial","logit",500)
NB_times<-100

ALPHA_PROP<-0.10
K<-4
typeS<-"simple"

LIST_ML<-list()
L_L2_simul<-LIST_ML
L_A_X_simul<-LIST_ML
L_L2_obs<-LIST_ML
L_A_X_obs<-LIST_ML

DATA_for_gg_ML<-c()
DATA_for_gg_ML_L2<-c()
DATA_for_gg_ML_Angle<-c()
Time_found<-list()
```


```{r}

for(nameV in names(list_simul)){
  
  result<-matrix(NA,nrow = 3,ncol = 3)
  Reals<-list_obs[[nameV]]
  Simuls<-list_simul[[nameV]]
  Time_found[[nameV]]<-rep(nameV,ncol(Simuls))
  Lperfs_Y<-Running_perfs_ML(
          Base_simul = Simuls,Base_data = Reals, 
          hyp_param = H_Params, NB_times =NB_times,
          alpha_prop=ALPHA_PROP,K = K, 
          type_sampling = typeS,title_ROC =nameV,
          NB_shown_ROC = 20)
  
  New_df<-Lperfs_Y$df_for_graphics
  Cplmt<-rep(nameV,
             nrow(New_df))
  New_df$variable<-Cplmt
  DATA_for_gg_ML<-rbind(DATA_for_gg_ML,
                        New_df)
  RF_sim<-(rowSums(Simuls^2))**(1/2)
  RF_obs<-(rowSums(Reals^2))**(1/2)
  L_L2_simul[[nameV]]<-RF_sim
  L_L2_obs[[nameV]]<-RF_obs
  Lperfs_L2<-Running_perfs_ML(Base_simul = RF_sim,
                            Base_data = RF_obs, hyp_param = H_Params, 
                      NB_times =NB_times,alpha_prop=ALPHA_PROP,K = K, 
                       type_sampling = typeS,
                    title_ROC =nameV,
                       NB_shown_ROC = 20)

  New_df_L2<-Lperfs_L2$df_for_graphics
  New_df_L2$variable<-Cplmt
  DATA_for_gg_ML_L2<-rbind(DATA_for_gg_ML_L2,
                        New_df_L2)

  Angle_Sim<-t(t(Simuls)%*%diag((RF_sim+1)^(-1)))
  Angle_Obs<-t(t(Reals)%*%diag((RF_obs+1)^(-1)))
  L_A_X_simul[[nameV]]<-Angle_Sim
  L_A_X_obs[[nameV]]<-Angle_Obs
  
  Lperfs_Angle_Y<-Running_perfs_ML(Base_simul = Angle_Sim,
              Base_data = Angle_Obs, hyp_param = H_Params, 
            NB_times =NB_times,alpha_prop=ALPHA_PROP,K = K, 
             type_sampling = typeS,title_ROC =nameV,
             NB_shown_ROC = 20)

  New_df_Angle<-Lperfs_Angle_Y$df_for_graphics
  New_df_Angle$variable<-Cplmt
  DATA_for_gg_ML_Angle<-rbind(DATA_for_gg_ML_Angle,
                           New_df_Angle)
  result[1,]<-Lperfs_Y$Accuracy$qu_accuracy
  result[2,]<-Lperfs_L2$Accuracy$qu_accuracy
  result[3,]<-Lperfs_Angle_Y$Accuracy$qu_accuracy
  rownames(result)<-c("X","L(X)","A(X)")
  colnames(result)<-c("SVM","GLM","RF")
  write.csv(file = paste0(ML_path,"/",nameV,"_ML_result_",
                Prefix,"_", D,".csv")
            ,x = result)
}

```

```{r}
### Assemble the predictions
LIST_ML[["X"]]<-DATA_for_gg_ML
LIST_ML[["L2"]]<-DATA_for_gg_ML_L2
LIST_ML[["Angle_X"]]<-DATA_for_gg_ML_Angle

for(name_elt_gg in names(LIST_ML)){
  ### Different ML results summarised
  GG_summary_MV<-ggplot2::ggplot(data = LIST_ML[[name_elt_gg]],
                aes(y=value))+
    geom_violin(aes(x=model,fill=model),alpha=0.7)+
    facet_wrap(~variable,scales="free_y")+
    geom_boxplot(aes(x=model),alpha=0.3,width=0.3)+
    ylab("Accuracy")+
    labs(fill="Legend")+
    xlab(NULL)+
    theme(axis.text.x = element_blank(),
          axis.ticks.x = element_blank())+
    geom_hline(aes(yintercept=0.5),col="red",
               linetype="dashed")
  ggsave(filename =  paste0(ML_path,"/summary_results_",
                              name_elt_gg,".png"),
         width = 6,height=6,plot = GG_summary_MV)
  
}
```

```{r}
# MLearning with multivariate time series ----------------
#######

### X -------------
Simuls_MV<-do.call(cbind, list_simul)
colnames(Simuls_MV)<-c(1:ncol(Simuls_MV))
Reals_MV<-do.call(cbind, list_obs)
colnames(Reals_MV)<-colnames(Simuls_MV)

### L_X ---------------
L_L2_simul_MV<-do.call(cbind, L_L2_simul)
L_L2_reals_MV<-do.call(cbind, L_L2_obs)

### A(X) ------------------
A_X_simul_MV<-do.call(cbind, L_A_X_simul)
A_X_reals_MV<-do.call(cbind, L_A_X_obs)
colnames(A_X_reals_MV)<-c(1:ncol(A_X_reals_MV))
colnames(A_X_simul_MV)<-colnames(A_X_reals_MV)
```


```{r}
# Run fitting ---------------------------------------------------------------
#################
### Run the classification two-sample test with three types of input

result_MV<-matrix(NA,ncol=3,nrow=3)

### (1) Concatenated raw time series --------------
####################
LIST_MV_ML<-list()
LIST_MV_ML[["X"]]<-Running_perfs_ML(Base_simul = Simuls_MV,
                            Base_data = Reals_MV, 
                           hyp_param = H_Params, 
                           NB_times =NB_times,alpha_prop=ALPHA_PROP,
                           K = K, 
                           type_sampling = typeS,
                          title_ROC ="MV case",
                           NB_shown_ROC = 20)
result_MV[,1]<-LIST_MV_ML[["X"]]$Accuracy$qu_accuracy

### (2) d-dimensional vector of  maximum value--------------
###################
LIST_MV_ML[["L2"]]<-Running_perfs_ML(Base_simul = L_L2_simul_MV,
                      Base_data =L_L2_reals_MV, 
                      hyp_param = H_Params,
                      NB_times =NB_times,alpha_prop=ALPHA_PROP,K = K, 
                      type_sampling = typeS,
                      title_ROC ="L2 MV case",
                      NB_shown_ROC = 20)
result_MV[,2]<-LIST_MV_ML[["L2"]]$Accuracy$qu_accuracy

### (3) Concatenated angular time series-------------------
###################
LIST_MV_ML[["A_X"]]<-Running_perfs_ML(Base_simul = A_X_simul_MV,
                      Base_data =A_X_reals_MV, 
                      hyp_param = H_Params, 
                      NB_times =NB_times,
                      alpha_prop=ALPHA_PROP,K = K, 
                      type_sampling = typeS,
                      title_ROC ="Angle MV case",
                      NB_shown_ROC = 20)
result_MV[,3]<-LIST_MV_ML[["A_X"]]$Accuracy$qu_accuracy

```

```{r}
# Export of the results ---------
#############
rownames(result_MV)<-c("X","L_X","A(X)")
colnames(result_MV)<-c("SVM","GLM","RF")
write.csv(file = paste0(ML_path,"/MV_ML_result_",
                Prefix,"_", D,".csv")
          ,x = result_MV)
```

```{r}
# End of the code --------------------------------------------------
#########
stopCluster(heartsCPU)
```

