```{r,message=FALSE,warning=FALSE}
rm(list=ls())
set.seed(133)
par(mfrow=c(1,1))

#### Import packages #####
require(dplyr)
require(ggplot2)
require(reshape2)
require(FactoMineR)
require(extRemes)
require(fda)
require(parallel)
require(VineCopula)
require(grid)
require(gridExtra)
require(mvPot)
require(stringr)

```

```{r,message=FALSE,warning=FALSE}
#Functions from univariate case. 
source("functions/fonctions_Pareto.R")
source("functions/fonctions.r")
#source("fonctions/fonctions_r_pareto_EVOLTAU.r")

### Generation functions
source("functions_MV/functions_generation_MV.R")
source("functions_MV/functions_simul_MV.R")
### Source des fonctions. ####
F_names<-ls()
nb_hearts<-detectCores()-4


# Defining clusters --------------------------------------------------
hearts<-makeCluster(nb_hearts)
clusterExport(hearts,varlist=F_names)
COMMON_theme<-theme(axis.title = element_text(size=20),
                    strip.text=element_text(size=20),
                    legend.title = element_text(size=20),
                    legend.text=element_text(size=17),
                    axis.text=element_text(size=17))
```

```{r}

G_used<-"max"
if(G_used=="max"){
  gl<-function(x){max(x)}
}
q<-20
FSIZE<-15
G_used2<-G_used
if(G_used=="Weighted_NQ"){
  G_used2<-paste0(G_used2,"_q=",q)
}
Link_resid<-paste0("residuals_MV/")
path_graph<-paste0(getwd(),"/Graphics_MV/data")
ROOT_export_graph<-paste0(path_graph,"/",
                          G_used,"/")
### Options fo the simulation
#Prefix<-paste0(CPLMT_graph_theta,"_",METHOD_ANGLE)
Prefix<-""
Approach<-"HTawn"
if(Approach=="AD"){
  if(List_Params_RF[["parametric"]]==TRUE){
    opt_used<-paste0("_",MODEL_used)
  }else{
    opt_used<-paste0("_np")
  }
  
}else{
  opt_used<-Approach
}
```


```{r}

METHOD_MGtransf<-"_Mixt_transf_"

lNAME<-c("Hs","U","Surcote")
d<-length(lNAME)

Subfix_sim<-paste0(METHOD_MGtransf,"_",opt_used,"_d=",d)
Subfix_data<-paste0(METHOD_MGtransf,"_d=",d)
lNAME<-c("U","Surge","Hs")

link_export_<-paste0("Generated_extremes/",G_used2,"/")
try({
  dir.create(file.path(link_export_))
})
```

```{r}
#### Option for the choice of previous time series
OPT_USED<-"KNN"

cols_<-c("data"="blue","simulations"="orange",
         "confidence_band"="darkblue",
         "model"="red","Storm"="black", "exceedances"="red",
         "real_data"="black")
require(cowplot)
require(patchwork)
DF<-read.csv(file =paste0("data_detrend_Winter/dates.csv"))
Dates_Joh<-c("08/03/2008","09/03/2008",
             "10/03/2008")
Dates<-substr(DF$x,start = 1,stop = 10)
sub_Ind_j<-Dates_Joh[which(Dates_Joh%in%Dates)]
Previous<-sub_Ind_j[1]

#### KNN-based approach
KCHOSEN<-15
```


```{r}
### (1) K-fold cross validation--> compare performances with different number of
### neighbors
###########
NUMBER_FOLD_CrossValid<-10
### Candidate number of neighbors
VECTOR_K<-seq.int(from = 5,to = 40,
                  by = 5)

### two options
### a) sample with probability the previous time series
### b) take for each forcing condition a theoretical "mean" previous time series
# CV_results_perK<-K_fold_k_param( hearts = hearts,
#                 list_variable = lNAME,
#                 link_import_residuals = Link_resid,
#                 f_distance = distance_sq,Name_riskF=G_used2,
#                 number_Kfold = NUMBER_FOLD_CrossValid,
#                 type_donnees = "HIVER",
#                 vector_K = VECTOR_K)
# melting_CV_list<-as.data.frame(melt(CV_results_perK))
# 
# colnames(melting_CV_list)<-c("value","hyper_param")
# melting_CV_list$hyper_param<-VECTOR_K[melting_CV_list$hyper_param]
# melting_CV_list$hyper_param<-as.character(melting_CV_list$hyper_param)
# melting_CV_list
# 
# results_per_K<-melting_CV_list %>%
#   group_by(hyper_param) %>%
#   summarise(meanV=mean(value))
# results_per_K
# melting_CV<-as.data.frame(results_per_K)
# melting_CV$hyper_param<-as.numeric(melting_CV$hyper_param)
# colnames(melting_CV)<-c("hyper_param",
#                         "value")
# EXPR_Kchosen<-expression(n[KNN])
# melting_CV$hyper_param<-as.numeric(melting_CV$hyper_param)
# GG_CV_metrics<-ggplot2::ggplot(melting_CV)+
#   #facet_wrap(~stat,scales = "free_y")+
#   geom_line(aes(x=hyper_param,y=value))+
#   guides(col="none")+
#   xlab("Number of neighbors")+
#   ylab("Mean Accuracy (CV)")+
#   geom_vline(aes(xintercept=KCHOSEN,
#                  linetype="nkNN"))+
#   scale_linetype_manual(
#     values = 3,
#     labels=EXPR_Kchosen)+labs(linetype="Legend")+
#   theme(legend.direction = "horizontal",
#         axis.title=element_text(size=FSIZE),
#         strip.text=element_text(size=13),
#         legend.title = element_text(size=14),
#         legend.text=element_text(size=13),
#         legend.position = "bottom")+
#   COMMON_theme
# GG_CV_metrics
# ggsave(filename = paste0("graphiques_MV/data/",G_used2,
#                          "/CV_metrics_KNN.png"),
#        plot = GG_CV_metrics,width=10,height=6)
```

```{r}
###predict the second obs
######################

IndJohanna<-which(Dates==Previous)
Date_predicted<-unlist(DF$x)[IndJohanna+1]
Unit_variable<-list("Surcote"="(m)","U"="(m/s)",
                    "Hs"="(m)")
common_linetype<-scale_linetype_manual("Legend",
                                       values=c("confidence_band"=2,
    "mean"=5,"real_data"=4))

```
```{r}
REPERTORY_<-"data_detrend_Winter/"
Output<-Generator_TSERIES_MV(hearts = hearts,list_variable = lNAME,
            link_import_residuals = Link_resid,
            prefix_link_resid=Prefix,
            subfix_link_Sim=Subfix_sim,
            subfix_link_Data=Subfix_data,
            link_export_generations=link_export_,
            link_rootVAR_model = "whitening_MV/",
            K_chosen = KCHOSEN,f_distance = distance_sq,
            cols_gg = cols_,Name_riskF=G_used2,
            Vect_VARtimes=c(1:37),
            Dates_Johanna=IndJohanna,Risk_Function=gl,
            opt_used=OPT_USED,repertory_data=REPERTORY_)
```


```{r}
### Comparing taken previous time series with the counterpart for 
### extreme observations
Z<-1
L_Data_Ext<-Output$Target
L_Sim<-Output$Result

for(nameV in names(Output$X0)){
 
  # Reals_1<-L_Data_Ext[[nameV]]
  # Simuls_1<-L_Sim[[nameV]]
  Correct_name<-Fct_correct_name(x = nameV,
                                 target = "Surcote",
                                 replacement = "Surge")
  # DF_gene<-rbind.data.frame(Reals_1,Simuls_1)
  # DF_gene$origin<-c(rep("data_ext",nrow(Reals_1)),
  #                   rep("sim_ext",nrow(Simuls_1)))
  # write.csv(file=paste0(Metamod_path,"/",Correct_name,"_data_sim.csv"),
  #           x = DF_gene,row.names = FALSE)
  #################
  
  
  YLEFT<-paste0(Correct_name,Unit_variable[[nameV]])
  XO_v<-Output$X0[[nameV]]
  Max_taken<-apply(X = XO_v,MARGIN = 1,FUN = max)
  Prev_target_v<-Output$previous_target[[nameV]]
  Max_previous_target<-apply(X =Prev_target_v,
                             MARGIN = 1,FUN = max)
  ### Comparing sampled previous time series
  ## with the one of extreme events
  Taken_previous<-as.data.frame(c(Max_taken,Max_previous_target))
  colnames(Taken_previous)<-c("value")
  Taken_previous$origin<-c(rep("taken",length(Max_taken)),
                           rep("previous_target",
                              length(Max_previous_target)))
 

  GGtaken<-ggplot2::ggplot(Taken_previous)+
    geom_violin(aes(x=origin,y=value,fill=origin),
                 alpha=0.7)+
    geom_boxplot(aes(x=origin,y=value),width=0.3,
                 fill="grey")+
    ylab(YLEFT)+
    xlab(NULL)+
    theme(legend.direction="horizontal",
          axis.text.x = element_blank(),
           axis.ticks.x = element_blank(),
          axis.title=element_text(size=FSIZE),
          legend.text=element_text(size=10))+
    labs(fill="Legend")
  
  ### Comparing relation (Y_prev vs Epsi) found in Data vs simulations
  ########
  Target_v<-Output$Target[[nameV]]
  Max_target<-apply(X =Target_v,
                    MARGIN = 1,FUN = max)
  Sim_v<-Output$Result[[nameV]]
  Max_simV<-apply(X =Sim_v,
                  MARGIN = 1,FUN = max)
  Relation_data<-cbind.data.frame(Max_previous_target,
                                  Max_target)
  colnames(Relation_data)<-c("previous","value")
  Relation_sim<-cbind.data.frame(Max_taken,
                                 Max_simV)
  YLEFT<-paste0(Correct_name,Unit_variable[[nameV]])
  colnames(Relation_sim)<-colnames(Relation_data)
  Relations_whole<-rbind.data.frame(Relation_data,
                                    Relation_sim)
  Relations_whole$Legend<-c(rep("data",nrow(Relation_data)),
                            rep("simulations",nrow(Relation_sim)))
  GGRelation_found<-ggplot2::ggplot(Relations_whole,
                           mapping = aes(x=previous,y=value,
                      colour=Legend,shape=Legend))+
    ylab(paste0("max( ",YLEFT," )"))+
    xlab(expression("max prev"))+
    geom_point(aes(size=Legend))+
    scale_color_manual(values=cols_)+
    scale_shape_manual(values = 
                         c("simulations"=17,"data"=19))+
    scale_size_manual(values=
                        c("simulations"=0.75,"data"=1.5))+
    theme(legend.direction="horizontal",
          axis.title=element_text(size=FSIZE),
          legend.text=element_text(size=10))
  
  ### Relation Epsi Previous FOR EXTREMES
  ###
  Max_EP<-apply(X = Output$Epsi_data_ext[[nameV]],
                MARGIN = 1,FUN = max)
  Max_sim_EP<-apply(X = Output$Epsi_sim[[nameV]],
                    MARGIN = 1,FUN = max)
  Relation_dataEPREV<-cbind.data.frame(Max_previous_target,
                                  Max_EP)
  colnames(Relation_dataEPREV)<-c("previous","EPSI")
  Relation_dataEPREV<-cbind.data.frame(Max_previous_target,
                                       Max_EP)
  colnames(Relation_dataEPREV)<-c("previous","EPSI")
  
  Relation_simEPREV<-cbind.data.frame(Max_taken,
                                 Max_sim_EP)
  colnames(Relation_simEPREV)<-colnames(Relation_dataEPREV)
  

  Relations_wholeEPREV<-rbind.data.frame(Relation_dataEPREV,
                                         Relation_simEPREV)
  Relations_wholeEPREV$Legend<-c(rep("data",
                          nrow(Relation_dataEPREV)),
               rep("simulations",nrow(Relation_simEPREV)))
  GGRelation_EPSI_Prev<-ggplot2::ggplot(Relations_wholeEPREV,
                           mapping = aes(y=previous,x=EPSI,
                 colour=Legend,shape=Legend))+
    ylab(paste0("max( ",YLEFT," ) prev"))+
    xlab(expression("max"~epsilon))+
    geom_point(aes(size=Legend))+
    scale_color_manual(values=cols_)+
    scale_shape_manual(values = 
                         c("simulations"=17,"data"=19))+
    scale_size_manual(values=
                        c("simulations"=0.75,"data"=1.5))+
    theme(legend.direction="horizontal",
          axis.title=element_text(size=FSIZE),
          legend.text=element_text(size=10))
  
  if(Z==1){
    LEGEND_used<-get_legend(GGtaken)
    LEGEND_2<-get_legend(GGRelation_found)
    LEGEND_3<-get_legend(GGRelation_EPSI_Prev)
    Cums_compar<-GGtaken+
      guides(fill="none")
    Cums_compar3<-GGRelation_EPSI_Prev+
      guides(col="none",size="none",
             shape="none")
  }else{
    Cums_compar<-Cums_compar+
      GGtaken+
      guides(fill="none")

    Cums_compar3<-Cums_compar3+
      GGRelation_EPSI_Prev+
      guides(col="none",size="none",
             shape="none")
  }
  Z<-Z+1
}
Graph_Max_sampled_EXT<-plot_grid(Cums_compar,LEGEND_used,
          rel_heights = c(7,1),ncol=1)
Graph_Max_sampled_EXT<-ggdraw()+
  draw_plot(Graph_Max_sampled_EXT)+
  theme(plot.background = element_rect(fill = "white", 
                                       color = NA))
ggsave(filename=paste0(ROOT_export_graph,"/max_previous_EXTS.png"),
       plot = Graph_Max_sampled_EXT,width=10,height = 6)

Graph_relEpsi_previous_EXT<-plot_grid(Cums_compar3,LEGEND_3,
          rel_heights = c(7,1),ncol=1)
Graph_relEpsi_previous_EXT<-ggdraw()+
  draw_plot(Graph_relEpsi_previous_EXT)+
  theme(plot.background = element_rect(fill = "white", 
                                       color = NA))
ggsave(filename=paste0(ROOT_export_graph,
                       "/rel_Epsi_previous_observation_EXTS.png"),
       plot = Graph_relEpsi_previous_EXT,width=10,height = 6)
```

```{r}
### Export predictions for Johanna event
J<-1
Time_label<-"Time (hour) with respect to tidal peak"

Nshown<-50
for(NV in lNAME){
  TJ<-Output$target_Johanna[[NV]]
  Sim_TJ<-Output$predictions_Johanna[[NV]]
  
  NB_sample<-sample(c(1:nrow(Sim_TJ)),
                    size = Nshown,replace = FALSE)
  Melteur<-melt(t(Sim_TJ[NB_sample,]))
  colnames(Melteur)<-c("Time","Index","valeur")
  Melteur$Index<-as.character(Melteur$Index)

  M2<-melt(t(TJ))
  colnames(M2)<-c("Time","Index","valeur")
  M2$Index<-rep(1,nrow(M2))
  M2$Index<-as.character(M2$Index)
  M2<-M2[,colnames(Melteur)]
  Timenorm<-M2$Time-min(unlist(M2$Time))+1
  estimator_025_simul<-apply(Sim_TJ,MARGIN =2,
         function(x){
           return(as.numeric(quantile(x,0.025)))})
  estimator_975_simul<-apply(Sim_TJ,MARGIN =2,
         function(x){
           return(as.numeric(quantile(x,0.975)))})
  mu1<-apply(X = Sim_TJ,MARGIN = 2,FUN = mean)
  Timenorm_sim<-Melteur$Time-min(unlist(Melteur$Time)
  )+1
  Melteur$bound_inf<-estimator_025_simul[Timenorm_sim]
  Melteur$bound_sup<-estimator_975_simul[Timenorm_sim]
  Melteur$mu<-mu1[Timenorm_sim]
  M2$Time<-(M2$Time-19)/6
  Melteur$Time<-(Melteur$Time-19)/6
  
  Whole<-Melteur
  Whole$Index <- as.factor(Whole$Index)
  Nv_correct<-Fct_correct_name(x =NV,target = "Surcote",
                               replacement = "Surge")
  yleft<-paste0(Nv_correct," ",
         Unit_variable[[NV]])
  mid<-which(M2$Time==0)
  Df_for_annotate<-cbind.data.frame(0,unlist(M2$valeur)[mid],
                                    Date_predicted)
  colnames(Df_for_annotate)<-c("xspec","yspec","label_spec")
  GGsum<-ggplot2::ggplot(data=Whole,
                aes(x=Time,y=valeur
                ))+
    geom_text(
      data=Df_for_annotate,
      aes(x=xspec,y=yspec,label=label_spec),
      size=4,col="darkblue")+
    geom_ribbon(aes(ymin=bound_inf,ymax=bound_sup,
                    linetype="confidence_band",
                    group=1),
                alpha=0.15,fill="grey",
                col="darkblue")+
    geom_line(aes(x = Time,y=mu,linetype="mean"),
              col="red",size=1.1)+
    guides(col="none")+
    geom_line(alpha=0.7,aes(col=Index))+
    geom_line(data = M2,aes(x=Time,y=valeur,
                      linetype="real_data"),
              alpha=0.9)+
    xlab(Time_label)+
    ylab(yleft)+common_linetype+
    labs(linetype="Legend")+
    theme(legend.direction = "horizontal",
          axis.title=element_text(size=FSIZE),
          strip.text=element_text(size=13),
          legend.title = element_text(size=14),
          legend.text=element_text(size=13))
  GGsum2<-GGsum+
    theme(legend.position = 'none',
          legend.direction = "horizontal")
  if(J==1){
    Cum_exs_simuls<-GGsum2
    LEGEND_exs<-get_legend(GGsum)
    
  }else{
    Cum_exs_simuls<-Cum_exs_simuls+
      GGsum2
  }
  J<-J+1
}

```
```{r}
LGD_exs<-plot_grid(LEGEND_exs)
intermed_plot_EXS<-Cum_exs_simuls+
  plot_layout(axis_titles = "collect_x")
final_plot_EXS<-plot_grid(intermed_plot_EXS,LGD_exs,ncol=1,
                          rel_heights =c(10,1))
f_EXS_export<-ggdraw()+
  draw_plot(final_plot_EXS)+
  theme(plot.background = element_rect(fill = "white", 
                                       color = NA))
f_EXS_export
ggsave(filename = paste0(ROOT_export_graph,"/exs_simuls_Johanna_",Approach,
                         "_d=",length(lNAME),".png"),
       plot = f_EXS_export,width=10,height = 6)
```


```{r}
# End of the code ---------------------------------------------------------
###################
stopCluster(hearts)

```





