```{r}
rm(list=ls())
set.seed(133)
par(mfrow=c(1,1))

#### Import des packages. #####
require(cowplot)
require(ggguides)
require(copula)
require(latex2exp)
require(dplyr)
require(ggplot2)
require(reshape2)
require(FactoMineR)
require(extRemes)
require(fda)
require(parallel)
require(VineCopula)
require(grid)
require(gridExtra)
require(mvPot)
require(ggside)
require(mev)
require(scales)
require(gamlss)
require(texmex)
require(patchwork)

COMMON_theme<-theme(axis.title = element_text(size=20),
                    strip.text=element_text(size=20),
                    legend.title = element_text(size=20),
                    legend.text=element_text(size=17),
                    axis.text=element_text(size=17))
### Source des fonctions. ####
#Functions from univariate case. 
source("../fonctions/fonctions_Pareto.R")
source("../fonctions/fonctions.r")
source("../fonctions/fonctions_r_pareto_EVOLTAU.r")

#Specific multivariate functions. 
source("functions_MV/function_simul_MV.r")
source("functions_MV/functions_Angle_MV.r")
source("functions_MV/F_simulations_cond.R")
source("functions_MV/GenericEGPDg_carrer.R")
# import G pareto ---------------------------------------------------------
source("functions_MV/function_estim_simul_gPareto.R")
source("functions_MV/Stat_test_MV.R")
source("functions_MV/Hidden_RV_functions.R")

# Choice of threshold -----------------------------------------------------
source("Choice_auto_thresh/src/eqd.R")
source("Choice_auto_thresh/src/helper_functions.R")

# Consistency results -----------------------------------------------------
source("functions_MV/Fonctions_consistency.R")

F_names<-ls()
nb_coeurs<-detectCores()-4
```

```{r}
# Ouverture des clusters --------------------------------------------------
coeurs<-makeCluster(nb_coeurs)
clusterExport(coeurs,varlist=F_names)
cols_<-c("data"="blue","simulations"="orange",
         "confidence_band"="darkblue",
         "model"="red","threshold"="red",
         "egpd"="#00BE67",
         "mixture"="blue")
Shapes_<-c("candidates"=0,
          "threshold"=1)

l_root<-"residuals_MV/"
path <- paste0(getwd(),"/residuals_MV")
l_name<-c("Surcote","Hs","U")
newfolder <- "Conversion"
#METHOD_MGtransf<-"_EGPD_transf_"
METHOD_MGtransf<-"_Mixt_transf_"
METHOD_ANGLE<-"GaussMixture"

#Prefix<-paste0(CPLMT_graph_theta,"_",METHOD_ANGLE)
Prefix<-""
Name_model<-"hr"
try({
  dir.create(file.path(path, newfolder))
})
path_conversion<-paste0(path,"/",newfolder,"/")
path_graph<-paste0(getwd(),"/graphiques_MV/resid/")

### Import conversion and original data
Result_MV<-list()
SUMMARY<-list()
SUMMARY_convergence<-list()
DF_RF<-list()
DF_orig<-list()
ALL_transf<-list()
#Try with 1/4
Shape_chosen<-2/5

### Mean of the GPD law to use extremal correlation coefficient
CGPD<-Shape_chosen/(1-Shape_chosen)
comment_go<-latex2exp::TeX("$\\gamma_{0}$")
d<-length(l_name)

##########
XLAB<-'Time(hour) with respect to tidal peak'
TITLE<-ggdraw() +
  draw_label(XLAB,size=20)
Z_seen<-1
YLIM<-c(0,5)
YTheta_Lim<-c(0,2)
NV_DKG<-"Hs"
###[,c(2:38)]
DF_transf<-read.csv(file = paste0(path_conversion,NV_DKG,
                                  METHOD_MGtransf,d,".csv"))
Variable_ref<-DF_transf[,19]
ind_DKG<-order(Variable_ref,decreasing = TRUE)[1:4]

DROP_DKG<-FALSE
DATES<-read.csv(file = "../ss_tend/HIVER/dates_prises.csv")[,2]
DATES[ind_DKG]

```


```{r}

for(nameV in l_name){
  ###[,c(2:38)]
  DF_transf<-read.csv(file = paste0(path_conversion,nameV,
                                METHOD_MGtransf,d,".csv"))
  ### remove pbtic value
  if(DROP_DKG){
    DF_transf<-DF_transf[-ind_DKG,]
  }
  
  ### Convert_to_Pareto(pow_transform)
  DF_transf<-(DF_transf+1)^(Shape_chosen)-1
  
  rf_j<-apply(X = DF_transf,MARGIN = 1,FUN = calcul_norm_L2)
  ### Export Z_vs_Theta with nameV
  ##############
  Inds_shown<-sample(c(1:nrow(DF_transf)),size = 20,
                  replace = FALSE)
  DF_mini<-DF_transf[Inds_shown,]
  Cpdg_L2<-rf_j[Inds_shown]
  Cpdg_theta<-t(t(DF_mini)%*%diag(Cpdg_L2^(-1)))
  Melting_df<-melt(t(DF_mini))
  Melting_theta<-melt(t(Cpdg_theta))
  colnames(Melting_df)<-c("Time","index","value")
  colnames(Melting_theta)<-c("Time","index","value")
  Melting_df$Time<-as.numeric(substr(Melting_df$Time,start = 2,
                                     stop = 3))
  Melting_df$Time<-(Melting_df$Time-19)/6
  Melting_theta$Time<-Melting_df$Time
  Melting_df$index<-as.character(Melting_df$index)
  Melting_theta$index<-Melting_df$index
  
  #### print variable name
  nameGraph<-Fct_correct_name(x = nameV,
                      target = "Surcote",
                      replacement = "Surge")
  Variable<-paste0("T(",nameGraph,")")
  Df_for_annotate<-cbind.data.frame(0,3,Variable)
  colnames(Df_for_annotate)<-c("xspec","yspec",
                               "label_spec")
  #### 
  Melting_df$forcg_cond<-rep(Variable,
                             nrow(Melting_df))
  if(Z_seen==1){
    YLAB<-paste0("Series")
    YLAB_univ<-paste0("Series of ",Variable)
    YLAB_theta<-paste0("Angle series (.)")
    YLAB_theta_univ<-paste0("Angle series of ",Variable)
  }else{
    YLAB<-NULL
    YLAB_theta<-NULL
  }
  GG_Zuniv<-ggplot(data=Melting_df)+
    geom_line(aes(x=Time,
                  y=value,group=interaction(index),
                  col=index))+
    ylab(YLAB_univ)+xlab(NULL)+
    scale_y_continuous(limits = YLIM)+
    COMMON_theme+
    guides(col="none")
  GG_Z<-ggplot(data=Melting_df)+
    geom_line(aes(x=Time,
                      y=value,group=interaction(index),
                      col=index))+
    geom_text(
      data=Df_for_annotate,
      aes(x=xspec,y=yspec,label=label_spec),
      size=10)+
    ylab(YLAB)+xlab(NULL)+
    scale_y_continuous(limits = YLIM)+
    COMMON_theme+
    guides(col="none")
  
  ### GG theta
  ########
  GG_Theta_univ<-ggplot(data=Melting_theta,aes(x=Time,
                          y=value,
                          group=interaction(index),
                            col=index))+
    geom_line()+
    ylab(YLAB_theta_univ)+xlab(NULL)+
    scale_y_continuous(limits=YTheta_Lim)+
    COMMON_theme+
    guides(col="none")
  
  GG_Theta<-ggplot(data=Melting_theta,aes(x=Time,
            y=value,group=interaction(index),
            col=index))+
    geom_line()+
    ylab(YLAB_theta)+xlab(NULL)+
    scale_y_continuous(limits=YTheta_Lim)+
    COMMON_theme+
    guides(col="none")
  GG_sum<-GG_Z+GG_Theta+
    plot_layout(axis_titles = "collect",
                ncol = 1,nrow=2)
  
  ###### Z vs theta univ
  GGsum_unif<-GG_Zuniv+GG_Theta_univ+
    plot_layout(axis_titles = "collect",
       ncol = 2,nrow=1)
  ggh_univ<-plot_grid(GGsum_unif,TITLE,
                 ncol=1,nrow=2,
                 rel_heights = c(12,1))
  plot_ggh_univ<-ggdraw()+
    draw_plot(ggh_univ)+
    theme(plot.background = element_rect(fill = "white", 
                                         color = NA))
  ggsave(filename = paste0(path_graph,"Z_vs_Theta_d="
             ,d,"_",nameGraph, ".png"),
        plot = plot_ggh_univ, width = 10,height = 6)
  
  if(Z_seen==1){
    Combn_Z_vs_Theta<-GG_sum
  }else{
    ### 
    Rest<-(Z_seen-1)
    Combn_Z_vs_Theta<-plot_grid(Combn_Z_vs_Theta,
            GG_sum,rel_widths = c(Rest,1))
  }

  #################
  DF_RF[[nameV]]<-rf_j 
  Link_j<-paste0(l_root,nameV,"_residuals_",
                 d,".csv")
  Orig_j<-read.csv(Link_j)
  ### Remove the DKG
  if(DROP_DKG){
    Orig_j<-Orig_j[-ind_DKG,]
  }
  DF_orig[[nameV]]<-Orig_j
  
  list_form<-list()
  PARAMS_GPD<-read.csv(file = paste0(path_conversion,nameV,
                                      "_GPD_params_",d,".csv"))
  K_hat<-read.csv(file = paste0(path_conversion,nameV,
                                "_Kdens_estim_",d,".csv"))
  list_form[["K"]]<-K_hat
  list_form[["LEVT"]]<-PARAMS_GPD
  
  SUMMARY[[nameV]]<-list("transf"=DF_transf,
                       "params_transfo"=list_form)
  ALL_transf[[nameV]]<-DF_transf
  Z_seen<-Z_seen+1
}

```

```{r}
ggh<-plot_grid(Combn_Z_vs_Theta,TITLE,
               ncol=1,nrow=2,
               rel_heights = c(12,1))
plot_ggh<-ggdraw()+
  draw_plot(ggh)+
  theme(plot.background = element_rect(fill = "white", 
                                       color = NA))
ggsave(filename = paste0(path_graph,"Z_vs_Theta_d="
        ,d,".png"),plot = plot_ggh,
       width = 10,height = 6)
###########
################

pow_tried<-seq.int(from = 2,to = 4,
                   length.out = 10)
k<-3
CHOSEN_var<-l_name[k]
T_chosen<-19
Precise_var<-ALL_transf[[CHOSEN_var]]
colnames(Precise_var)<-substr(colnames(Precise_var),
                              start = 2,stop = 3)
var_1<-Precise_var[,as.character(T_chosen)]
Mean_found<-sapply(pow_tried,
       FUN = function(x){
         return(mean(var_1^x))
       })
New_expr<-expression(Espcy (Z[comment_sub]^j) ^delta)
YLAB<-do.call("substitute", 
        list(New_expr[[1]], 
              list(j =T_chosen,
                   comment_sub=paste0("M,",k),
             Espcy="Mean of ")))
DF_summy<-cbind.data.frame(pow_tried,Mean_found)
colnames(DF_summy)<-c("delta","mean")

GG_RV_test<-ggplot(data=DF_summy,aes(x=delta,y=mean))+
  geom_line()+
  geom_point()+
  xlab(expression(delta))+
  ylab(YLAB)+
  geom_vline(aes(xintercept = 1/Shape_chosen,
                 col="chosen index"))+
  labs(col="Legend")
ggsave(filename = paste0(path_graph,"exs_RV_",
                         T_chosen,"_var=",
                         CHOSEN_var,".png"),
       plot = GG_RV_test,width = 6,height=6)
Inds_dates_pos<-read.csv(file=paste0(path_conversion,"inds_egpd.csv"))
Inds_dates_pos

```

```{r}

COLS_chosen<-c("gam_ref"="red",
               "ML_gamma"="blue",
               "confidence_band"="darkblue",
               "threshold"="red",
               "gam_ref"="black")
LINETYPE_chosen<-c("gam_ref"=3,
                   "Hill_gamma"=2,
                   "ML_gamma"=4,
                   "confidence_band"=5,
                   "threshold"=6,
                   "gam_ref"=6)

### Shape param transformation
##################
DIMS<-c(20,14,13,10)
YMV<-c(-0.5,1)
ALL_gam_transf<-list()
for(nameV in l_name){
  df_transf<-SUMMARY[[nameV]]$transf
  NL2_TF<-apply(X = df_transf,MARGIN = 1,FUN = calcul_norm_L2)
  GG_var<-Graphics_estimators_gamma(series = NL2_TF,
                                    vect_k = c(50:300),
                                    Title_graphic = " ",
                                    dims_elt_text = c(20,14,13,12),
                                    SELECT_estim = "ML_gamma")
  DF_tf_j<-GG_var$data
  DF_tf_j$variable<-rep(nameV,nrow(DF_tf_j))
  ALL_gam_transf[[nameV]]<-DF_tf_j
  # ggsave(filename = paste0(path_graph,"T",nameV,"_L2gamma.png"),
  #        plot = GG_var,height=4,width=6)
}
```

```{r}
DF_wholeTF<-do.call(rbind.data.frame,ALL_gam_transf)

DF_wholeTF$variable<-sapply(DF_wholeTF$variable,
                         FUN =function(x){
                           Fct_correct_name(x = x,target = "Surcote",
                                            replacement = "Surge")})
GGgam_tf<-ggplot(data=DF_wholeTF,aes(x=number_excesses,y =gamma_estimed,color=source,
                                    group=interaction(source),
                                    linetype=source))+
  geom_line()+
  facet_wrap(~variable)+
  ylab(expression(gamma))+
  xlab("Number of exceedances")+
  COMMON_theme+
  geom_ribbon(mapping = aes(ymin=bound_inf,ymax=bound_sup,
                            col="confidence_band",
                            linetype = "confidence_band"),alpha=0.15,
              fill="grey")+
  geom_hline(aes(yintercept=Shape_chosen,col="gam_ref",
                 linetype="gam_ref"))+
  labs(col="Legend", linetype = "Legend")+
  theme_bw()+
  theme(legend.direction = "horizontal",
        legend.position="bottom")
LABELS_shape<-names(COLS_chosen)

LEGEND_shape<-sapply(LABELS_shape,
                     function(x){
                       if(x=="gam_ref"){
                         return(comment_go)
                       }else{
                         return(x)
                       }
                     })
GG_gamtf_varwise<-GGgam_tf+
  scale_linetype_manual(values = LINETYPE_chosen,
                        labels=LEGEND_shape)+
  scale_color_manual(values = COLS_chosen,
                     labels=LEGEND_shape)+
  ylim(YMV)
ggsave(filename = paste0(path_graph,"/Tf_shape_varwise_d=",
                      length(l_name),".png"),
       plot=GG_gamtf_varwise,width = 8,height = 6)
```


```{r}

Result_MV<-list("resume"=SUMMARY,"orig"=DF_orig,
                "df"=as.data.frame(DF_RF),
                "type_transfo"=METHOD_MGtransf)
testw<-SUMMARY$Surcote$params_transfo$K
which(testw$time_analysed==1)
hh<-testw[,3]
namei<-l_name[1]
namej<-l_name[2]
t1<-1
t2<-37
couple<-cbind(Result_MV$orig[[namei]][,t1],
              Result_MV$orig[[namej]][,t2])
Filename<-paste0("graphiques_MV/asymp_dependencies/ext_dep_",namei,"_t=",t1,
                 "_",namej,"_tprime=",t2,".png")
png(filename = Filename,
    width=800,height=600)
par(mfrow = c(1, 2),  # 1 row, 2 plots
    cex.lab = 1,    # axis label size
    cex.axis = 1,   # axis tick label size
    cex.main = 1,   # main title size
    cex = 1)
Two<-expression(bar(chi))
POT::chimeas(data = couple,
             ask = FALSE,which=1,cex.lab=2)
POT::chimeas(data = couple,
             ask = FALSE,
             which=2,
             ylabs = rep(NA,2),
             cex.lab=1.5)
mtext(expression(bar(chi)),cex=2,las=2,
      outer=TRUE,line=-25)
par(mfrow=c(1,1))
dev.off()
Filename
expr_kunif<-function_expression_chi(j = 3,term = "chi")
print(expr_kunif)
Vect_l_function<-Result_MV$df
SUMMARY[[l_name[3]]]$transf
TEST_GPD_110<-apply(SUMMARY[[l_name[3]]]$transf,MARGIN = 2,
                FUN = evd::pgpd,
      loc=0,shape=Shape_chosen,scale=Shape_chosen)
head(TEST_GPD_110)
summary(SUMMARY[[l_name[3]]]$transf)
for (j in c(1:ncol(TEST_GPD_110))){
  print(goftest::ad.test(TEST_GPD_110[,j]))
}
```

```{r}
### Define the cost function used, angle estimation method 
### and number of simulations. 
M<-2000
ONE_PCA_BASIS<-TRUE
if(ONE_PCA_BASIS){
  LIST_NB_SCORES<-NULL
  ### 9
  NB_SCORES_OMEGA<-9
}else{
  LIST_NB_SCORES<-list("U"=4,"Surcote"=3,
                       "Hs")
  NB_SCORES_OMEGA<-NULL
}
q<-40
W_chosen<-c(0.3,0.7)
Name_riskF<-"max"
Name_riskF2<-Name_riskF
if(Name_riskF=="sum"){
  Risk_f<-function(x){return(sum(x))}
  wFun<-weightFun_sum
  dwFun<-DweightFun_sum
}
if(Name_riskF=="max"){
  Risk_f<-function(x){return(max(x))}
  wFun<-NA
  dwFun<-NA
}
if(Name_riskF=="sum_penalized"){
  Risk_f<-function(x){return(sum_penalized(x = x,vect_w = c(0.7,0.3)))}
  wFun<-function(x,u){
    weightFun_sum_penalized(x = x,u = u,
                            vect_w = W_chosen)
  }
  dwFun<-function(x,u){
    DweightFun_sum_penalized(x = x,u = u,
                             vect_w = W_chosen)
  }
}


if(Name_riskF=="Weighted_NQ"){
  Name_riskF2<-paste0(Name_riskF2,"_q=",q)
  Risk_f<-function(x){
    return(Norm_q(x=x,q=q,weights_nq = c(0.3,0.7)))
  }
  wFun<-function(x,u){
    return(weightFun_nq(x = x,u = u,
                        q = q,weights_nq = c(0.3,0.7)))
  }
  dwFun<-function(x,u){
    return(DweightFun_nq(x = x,u = u,
                         q = q,weights_nq = c(0.3,0.7)))
  }
}
```

```{r}
### Create subfolders

path <- paste0(getwd(),"/residuals_MV")
path_graph<-paste0(getwd(),"/graphiques_MV/resid")
newfolder <- Name_riskF2
try({
  dir.create(file.path(path, newfolder))
})
ROOT_export<-paste0(path,"/",Name_riskF2,"/")
try({
  dir.create(file.path(path_graph, newfolder))
})
ROOT_export_graph<-paste0(path_graph,"/",
                          Name_riskF2,"/")
try({
  Corr_path<-paste0(ROOT_export_graph,"Corr")
  dir.create(file.path(Corr_path))
  TEND_path<-paste0(ROOT_export_graph,"Tend")
  dir.create(file.path(TEND_path))
  Lg_path<-paste0(ROOT_export_graph,"RisKfunctions")
  dir.create(file.path(Lg_path))
  Theta_path<-paste0(ROOT_export_graph,"Theta")
  dir.create(file.path(Theta_path))
  PCA_path<-paste0(ROOT_export_graph,"PCA")
  dir.create(file.path(PCA_path))
  Extremo_path<-paste0(ROOT_export_graph,"extremes")
  dir.create(file.path(Extremo_path))
  for(name_V in l_name){
    newfolder<-name_V
    try({
      dir.create(file.path(TEND_path, newfolder))
      dir.create(file.path(Theta_path, newfolder))
      dir.create(file.path(PCA_path, newfolder))
      dir.create(file.path(Extremo_path, newfolder))
    })
  }
  
})
```

```{r}
# Analysis of asumptotic dependencies ----------
# within the radial vector------

Radial_vector<-Result_MV$df
Filename_DepRF<-paste0(path_graph,"/Asymp_dep_mat_d=",
                       ncol(Radial_vector),".png")
Filename_ADRF<-paste0(path_graph,"/AD_AItest_d=",
                      ncol(Radial_vector),".png")
l_name_modif<-sapply(l_name,Fct_correct_name,
                target = "Surcote",replacement = "Surge")
Var_graph_AD<-"radial components"
require(viridis)
Mat_dep<-Complete_chi_measure_analysis(
  Matrix_df_unif = VineCopula::pobs(Radial_vector),
  Order_quantile = 0.95,Filename = Filename_DepRF,
  Name_main = "",New_breaks_labels = l_name_modif)

### Test ad vs ai.
CMAT<-rbind(c(-0.3,-0.35,-0.35),
            c(-0.3,-0.3,-0.3),
            c(-0.3,-0.3,-0.3))
GG_found<-AD_test_analysis(Matrix_df = Radial_vector,
                 Mat_cthresh = CMAT,
                 Filename = Filename_ADRF,
                 Name_main = "",New_breaks_labels = l_name_modif,
                 THEME_ad_ai=COMMON_theme)

Vector_K<-c(50:400)
Vector_K2<-c(50:250)
Diags<-Run_diagnostics_Gamma_G(dims_elt_text =DIMS,
                               Vectors_HTAIL = Radial_vector,
                               Vect_k = Vector_K2,q = 0.8,
                               root_export = path_graph,
                               YLIM_MV = YMV)
```


```{r}
# 3) Running simulations  --------------------------------------------------
source("functions_MV/functions_Angle_MV.R")
USE_log<-FALSE
if(USE_log){
  CPLMT_graph_theta<-"With_log"
  FTF<-function(x){return(log(x))}
  FTF_inv<-function(x){return(exp(x))}
}else{
  CPLMT_graph_theta<-"Raw"
  FTF<-function(x){return(x)}
  FTF_inv<-function(x){return(x)}
}
## parametric=FALSE to use Legrand methods
Approach<-"HTawn"
optional_params<-NULL
if(Approach!="AD"){
  source("functions_MV/Helper_functions_Mouradhi.R")
  source("functions_MV/Radial_functions.R")
  require(tailDepFun)
  library(gtools)
  library(tidyverse)
  dyn.load("main.dll")
}
if(Approach=="HTawn"){
  optional_params<-c(0.70,0.75)
}
List_Params_RF<-list("parametric"=TRUE,"name_RF"=Name_riskF,
                     "function"=Risk_f,
                     "name_model"=Name_model,
                     "weightFunction"=wFun,
                     "dWeightFunction"=dwFun,
                     "init_opt_param"=0.5,
                     "Method_Angle"=METHOD_ANGLE,
                     "RF_Approach"=Approach,
                     "HTAWN_params"=optional_params,
                     "Shape_parameter"=Shape_chosen)

if(Approach=="AD"){
  if(List_Params_RF[["parametric"]]==TRUE){
    opt_used<-paste0("_",MODEL_used)
  }else{
    opt_used<-paste0("_np")
  }
  
}else{
  opt_used<-Approach
}

### For export
List_Params_RF[["general_option"]]<-opt_used

```


```{r}

# 2) Choice of the threshold -------------------------------------------------
### Convergence criterion for the correlation coefficient
Riskf_data<-apply(X = Vect_l_function,MARGIN = 1,
                  FUN = Risk_f)
Vector_K<-c(50:400)
GG_Exts_RF<-Graphics_estimators_gamma(series = Riskf_data,
                          vect_k = Vector_K2,
                          Title_graphic = " ",
                          dims_elt_text = c(20,14,13,12))
GG_Exts_RF
ggsave(filename = paste0(Lg_path,"/",l_name[1],
                         "_",l_name[2],"_d=",length(l_name),
                         "_extremes_shape.png"),
       plot =GG_Exts_RF,width=8,
       height = 6)

```

```{r}
### Pareto law of the cost functional of exceedances.
## Distance depends on a truncation of the density -------------------------
## So quite important ! ----------------------------------------------------

TS_param<-0.15

Result_k0_mad<-tea::mindist(data = Riskf_data,method = "mad",
                                ts =TS_param)
Result_k0_mad$tail.index
kstar2<-Result_k0_mad$k0

print(paste0("We would take ",kstar2,
             " extreme MV time series with MAD distance"))

# Using MAD distance to determine number of exts.------
kstar_test<-kstar2

# Associated quantile  ----
Qfound<-1-(kstar_test/length(Riskf_data))
Qfound
```

```{r}
Threshold_gamma_0<-as.numeric(quantile(Riskf_data,Qfound))
Inds_extremes<-which(Riskf_data>=Threshold_gamma_0)
Exceedances_RF<-Riskf_data[Inds_extremes]
```

```{r}
### Use update mindist to use evolution 
### of the metric

comment_thresh<-latex2exp::TeX("$u_{\\ell,g}$")
comment_gl<-latex2exp::TeX("$g_{\\ell}(.)$ metric value")

# Evolution of the metric -------------------------------------------------
# ######
METRIC_plot_used<-"mad"
k_metric<-mindist_update(data = Riskf_data,
                         ts = TS_param,method = METRIC_plot_used)
which.min(k_metric$value_metric)
Graphics_estimators_gamma(series = Riskf_data,
                          vect_k = c(50:200),
                          Title_graphic = "test")
kZero_found<-which.min(k_metric$value_metric)
Inds_subs_plot<-which(unlist(k_metric$Nb_k)%in%c(50:200))
k_metric_sub<-k_metric[Inds_subs_plot,]

Sub_graph_GamGl<-Graphics_estimators_gamma(series = Riskf_data,
                          vect_k = Vector_K2,
                          Title_graphic = " ",
                          dims_elt_text = c(20,16,14,13),
                          SELECT_estim = c("ML_gamma"),
                          COLS_chosen = COLS_chosen,
                          LINETYPE_chosen = LINETYPE_chosen)

```

```{r}
Sub_graph_GamGl_update<-Sub_graph_GamGl+
  geom_hline(aes(yintercept=Shape_chosen,col="gam_ref",
                 linetype="gam_ref"))+
  geom_vline(aes(xintercept=-1,col="threshold",
                 linetype="threshold"))+
  xlim(range(Vector_K2))+
  theme(legend.position="bottom")+
  COMMON_theme

Origin<-ggplot_build(Sub_graph_GamGl_update)$plot$scales$get_scales("colour")
Scale_col<-Origin$palette.cache
Origin_linetype<-Sub_graph_GamGl_update$scales$get_scales("linetype")
All_results_linetype<-Origin_linetype
Result<-ggplot_build(Sub_graph_GamGl_update)$plot$scales
LABELS<-names(Scale_col)
LEGEND_gam<-sapply(LABELS,
                   function(x){
                   if(x=="threshold"){
                          return(comment_thresh)
                   }
                   if(x=="gam_ref"){
                     return(comment_go)
                   }
                  if(x=="ML_gamma"){
                    return("ML estimator")
                  }else{
                    return(x)
                  }
                   })
LINETYPES<-linetype_pal()(length(LABELS))
v<-unlist(Scale_col)
Graph_label_value<-Sub_graph_GamGl_update+
  scale_linetype_manual(values=LINETYPES,
                        labels=LEGEND_gam)+
  scale_color_manual(values = v,
                        labels=LEGEND_gam)+
  COMMON_theme
Graph_label_value
```

```{r}
# Criterion choice ----------
###############

GG_criterion_first<-ggplot(k_metric_sub,
                           aes(x=Nb_k,
                               y=value_metric))+
  geom_line()+
  geom_vline(aes(xintercept=kstar2,
                 col="threshold"),
             linetype="dashed")+
  xlab("Number of exceedances")+
  ylab(comment_gl)+
  scale_color_manual(
    values = COLS_chosen)+
  scale_linetype_manual(LINETYPE_chosen)+
  labs(col="Legend")+
  theme_bw()+
  COMMON_theme+
  theme(legend.position="bottom",
        legend.direction = "horizontal")



```

```{r}
# Ggplot settings -----
############

Origin_criter<-ggplot_build(GG_criterion_first)$plot$scales$get_scales("colour")
Scale_col_criter<-Origin_criter$palette.cache
COLS_criter<-unlist(Scale_col_criter)
LABELS_criter<-names(Scale_col)
LEGEND_gam_criter<-sapply(LABELS_criter,
                   function(x){
                     if(x=="threshold"){
                            return(comment_thresh)
                     }
                     if(x=="gam_ref"){
                       return(comment_go)
                     }else{
                       return(x)
                     }
                   })
```


```{r}
GG_criterion_first<-GG_criterion_first+
scale_color_manual(values = COLS_criter,
                   labels=LEGEND_gam_criter)
GG_criterion_first

LGD_gam<-get_legend(Graph_label_value)
Sub_gam<-Sub_graph_GamGl_update+
  COMMON_theme+
  theme(legend.position="none")+
  xlab("(a)")
GG_criterion_up<-GG_criterion_first+
  theme(legend.position="none")+
  xlab("(b)")
require(patchwork)
GGextra<-(Sub_gam|GG_criterion_up) +
  plot_annotation(caption = "Number of exceedances",
                  theme = theme(
              plot.caption=element_text(size=20,
                                        hjust=0.5)))
Conv_Rad<-plot_grid(GGextra,LGD_gam,nrow=2,
          rel_heights = c(7,1))
f_Conv_Rad<-ggdraw()+
  draw_plot(Conv_Rad)+
  theme(plot.background = element_rect(fill = "white",
                                       color = NA))
f_Conv_Rad
### ADD legend using plot_grid.
ggsave(plot = f_Conv_Rad,
       filename = paste0(Lg_path,"/d=",
          length(l_name),"_criterion_Gl_metric_old_",
          METRIC_plot_used,".png"),
       width = 12,height=6)

```

```{r}
### Convergence of the angle
###########
Launch_graph_conv<-TRUE
if(Launch_graph_conv){
  Convgce_Angle_criterion<-Convgce_Angle_evol(
    liste_MV_Orig = ALL_transf,l_name = l_name,
    vector_k = Vector_K2,
    Ref_RiskF = Riskf_data)
  RUT<-lapply(Convgce_Angle_criterion,
              function(x){
                Melting<-melt(x)
                Dim_basis<-nrow(Melting)/length(l_name)
                Eigen_indices<-rep(c(1:Dim_basis),length(l_name))
                return(cbind(Melting,Eigen_indices))
              })
  nb_per_k<-nrow(RUT[[1]])
  k_tilde<-c(sapply(Vector_K2,function(x)
  {return(rep(x,nb_per_k))}))
  Melting_whole<-do.call(rbind.data.frame,RUT)
  Melting_whole<-cbind(Melting_whole,k_tilde)
  colnames(Melting_whole)<-c("value","forcg_cond",
                             "eigen_index","k")
  Melting_whole$eigen_index<-paste0("h[", 
                                    Melting_whole$eigen_index, 
                                    "]")
  Melting_whole$forcg_cond<-sapply(Melting_whole$forcg_cond,
                                   FUN = function(x){
                                     return(Fct_correct_name(x,target = "Surcote",
                                                             replacement = "Surge"))
                                   })
  COLORS_for_conv<-scale_fill_hue()$palette(length(l_name)+1)
  GG_conv_MV_Angle<-ggplot(Melting_whole)+
    facet_wrap(~eigen_index,
               scales = "free_y",
               labeller = label_parsed)+
    geom_vline(aes(xintercept= kstar2,
                   col="threshold"))+
    geom_line(aes(x=k,y=value,col=forcg_cond,
                  group=interaction(forcg_cond)))+
    labs(col="Legend")+
    xlab("Number of exceedances")+ylab("Mean projection")+
    COMMON_theme+
    theme(legend.position="bottom",axis.text = element_text(size=14))
  COLS_used<-ggplot_build(GG_conv_MV_Angle)$plot$scales$get_scales("colour")$palette.cache
  
  ### Respective labels
  h<-ggpubr::get_legend(GG_conv_MV_Angle)
  legendp_grobs9_11 <- unlist(h$grobs[[1]]$grobs[which(grepl("label", h$grobs[[1]]$layout$name))])
  ### grpel == rexp in python to select names respecting a given structure
  origin_label<-unname(legendp_grobs9_11[grepl("*text.*label$", 
                                               names(legendp_grobs9_11))])
  ## Modify to use expr
  label_convMV<-sapply(origin_label,
                       function(x){
                         if(x=="threshold"){
                           return(comment_thresh)
                         }else{
                           return(x)
                         }
                       })
  GG_conv_MV_Angle<-GG_conv_MV_Angle+
    scale_color_manual(
      labels=label_convMV,
      values=COLS_used
    )
  GG_conv_MV_Angle
  ggsave(paste0(ROOT_export_graph,"/Convergce_MVAngle_d=",
                length(l_name),".png"),
         plot = GG_conv_MV_Angle,width = 8,height = 5)
}
```

```{r}
if(Launch_graph_conv){
  ### Convergence of the extremal correlation coeff
  Evol_conv_criterion<-Extreme_cov_evol(
    liste_MV_Orig = ALL_transf,l_name = l_name,
    vector_k =Vector_K2,
    Ref_RiskF = Riskf_data,
    CPU_hearts = coeurs,center=CGPD)
}
if(Launch_graph_conv){

  KMAX<-length(Vector_K2)
  H_window<-10
  k_shown<-Vector_K2[c(H_window:KMAX)]
  ### Add stability plots based on standard deviation
  Evol_conv_criterion$pair_vars<-sapply(Evol_conv_criterion$pair_vars,
                                        FUN = function(x){
                                          return(Fct_correct_name(x,target = "Surcote",
                                                                  replacement = "Surge"))})
  pairs<-Evol_conv_criterion %>% 
    group_by(pair_vars) %>% summarise(count_=n())
  Pairs<-pairs$pair_vars
  Result_criterion_stability<-Evol_conv_criterion%>% 
    group_by(pair_vars) %>% 
    summarise(sigXY=Stability_criterion_choice_threshold(
      k_max = KMAX,bandwidth_h = H_window,series_sorted_stats=sigXY),
      rhoXY=Stability_criterion_choice_threshold(
        k_max = KMAX,bandwidth_h = H_window,series_sorted_stats=rhoXY),
      gamXY=Stability_criterion_choice_threshold(
        k_max = KMAX,bandwidth_h = H_window,series_sorted_stats=gamXY)
    )
  
  Result_criterion_stability$sigXY
  Nb_pairs<-length(l_name)*(length(l_name)-1)/2
  
  v_corr<-c("rho[kk']","sigma[kk']","gam[kk']")
  v_corr2<-c("rhoXY","sigXY","gamXY")
  EXPRESSIONS<-c(latex2exp::TeX("$\\rho_{kk'}$ value"),
                 latex2exp::TeX("$\\sigma_{kk'}$ value"),
                 latex2exp::TeX("$\\gamma_{kk'}$ value"))
  EXPRESSIONS_stab<-c(latex2exp::TeX("standard deviation of $\\rho_{kk'}$"),
                      latex2exp::TeX("standard deviation of $\\sigma_{kk'}$"),
                      latex2exp::TeX("standard deviation of $\\gamma_{kk'}$"))
  
  for(J in c(1:length(v_corr))){
    elt<-v_corr[J]
    elt2<-v_corr2[J]
    ### Stability ###
    ##############
    expr_j_stab<-EXPRESSIONS_stab[J]
    list_result<-Result_criterion_stability[,elt2][[1]]
    EVOL_std_whole<-Concatenate_entries_same_key(list_ = list_result,
                                                 key_target = "evol_std")
    beta_found_whole<-Concatenate_entries_same_key(list_ = list_result,
                                                   key_target = "beta_found")
    candidates_whole<-unlist(Concatenate_entries_same_key(list_ = list_result,
                                                          key_target = "candidates"))
    set_indexed_C<-which(names(list_result)=="candidates")
    vector_call_pvars<-c()
    J_seen<-1
    for(z_ind in c(1:length(set_indexed_C))){
      nber_candidates<-length(list_result[[set_indexed_C[z_ind]]])
      pair_studied<-Pairs[J_seen]
      vector_call_pvars<-c(vector_call_pvars,
                           rep(pair_studied,nber_candidates)
      )
      J_seen<-J_seen+1
    }
    stat_beta_whole<-Concatenate_entries_same_key(list_ = list_result,
                                                  key_target = "stat_beta")
    stat_cand_whole<-unlist(Concatenate_entries_same_key(list_ = list_result,
                                                         key_target = "stat_candidates"))
    Ratio<-length(EVOL_std_whole)/length(Pairs)
    Ratio_bfound<-length(beta_found_whole)/length(Pairs)
    Ratio_C<-length(candidates_whole)/length(Pairs)
    
    ### fill the required pair_vars column for each quantity of interest
    Pairs_whole<-c(sapply(Pairs,
                          FUN=function(x){
                            rep(x,Ratio)
                          }))
    Pairs_bFound<-c(sapply(Pairs,
                           FUN=function(x){
                             rep(x,Ratio_bfound)
                           }))
    
    df_stat_std<-data.frame(EVOL_std_whole,Pairs_whole)
    colnames(df_stat_std)<-c("value","pair_vars")
    df_stat_std$k<-rep(k_shown,Nb_pairs)
    df_beta<-data.frame(k_shown[beta_found_whole],
                        stat_beta_whole,
                        Pairs_bFound)
    colnames(df_beta)<-c("beta_f",
                         "value",
                         "pair_vars")
    df_C<-data.frame(k_shown[candidates_whole],
                     stat_cand_whole,
                     vector_call_pvars)
    colnames(df_C)<-c("C_f",
                      "value",
                      "pair_vars")
    GG_stab_j<-ggplot(data=df_stat_std)+
      facet_wrap(~pair_vars,scales = "free_y")+
      
      geom_line(aes(x=k,y=value,
                    col=pair_vars))+
      guides(col="none")+
      geom_vline(aes(xintercept=kstar2,
                     linetype="thresh"))+
      
      geom_point(data=df_C,aes(x=C_f,
                               y=value,
                               shape="candidates"))+
      geom_point(data=df_beta,aes(x=beta_f,
                                  y=value,
                                  shape="threshold"))+
      ylab(expr_j_stab)+
      xlab("Number of exceedances")+
      theme_bw()+
      COMMON_theme+
      theme(legend.position="bottom")+
      scale_shape_manual(values=Shapes_)+
      COMMON_theme+
      scale_linetype_manual(
        values = c(3),
        labels=c(comment_thresh)
      )+labs(linetype="Legend",
             shape=" ")+
      scale_color_manual(
        values = c(2,3,4),
        labels=unique(df_stat_std$pair_vars)
      )+
      guides(
        linetype = guide_legend(order = 1)  ,# First legend
        shape= guide_legend(order = 2)# Second legend
      )
    D_nameV<-length(l_name)
    ggsave(filename = paste0(ROOT_export_graph,"Corr/evol_stability_",elt,"_corr_d=",
                             D_nameV,".png"),
           plot=GG_stab_j,width = 4*D_nameV,height = 6)
  }
}
```

```{r}
if(Launch_graph_conv){
  ### Data confidence band for each correlation coefficient ####
  ################
  Conf_band<-Extreme_cov_confevol(liste_MV_Orig = ALL_transf,l_name = l_name,
                                  vector_k =Vector_K2,Ref_RiskF = Riskf_data,
                                  CPU_hearts = coeurs,center=CGPD,
                                  Nboot = 500,alpha_param = 0.05)
  
  Conf_band$pair_vars<-sapply(Conf_band$pair_vars,
                              FUN = function(x){
                                return(Fct_correct_name(x,target = "Surcote",
                                                        replacement = "Surge"))})
  
  centerGPD<-NULL
  colnames(Evol_conv_criterion)[c(2:4)]<-c("sigma[kk']",
          "rho[kk']","gam[kk']")
}
if(Launch_graph_conv){
  
  for(J in c(1:length(v_corr))){
    elt<-v_corr[J]
    elt2<-v_corr2[J]
    EXPRj<-EXPRESSIONS[J]
    gg<-Evol_conv_criterion[,c(elt,"pair_vars")]
    Conf_band2<-Conf_band[which(Conf_band$variable==elt2),]
    df_forgg<-melt(gg)
    df_forgg$pair_vars<-sapply(df_forgg$pair_vars,
                               FUN = function(x){
                                 return(Fct_correct_name(x,target = "Surcote",
                                                         replacement = "Surge"))})
    ratio<-nrow(df_forgg)/nrow(Evol_conv_criterion)
    df_forgg$k<-rep(Evol_conv_criterion$k,ratio)
    
    GGCorr_evol<-ggplot(df_forgg)+
      geom_line(aes(x=k,y=value,
                    group=interaction(pair_vars),
                    col=pair_vars))+
      facet_wrap(~pair_vars,
                 scales = "free_y")+
      guides(col="none")+
      geom_ribbon(data=Conf_band2,aes(x=k,ymin=Q1,ymax=Q2,
                                      linetype="confidence_band")
                  ,alpha=0.5,fill="lightgrey",
                  col="darkblue")+
      ylab(EXPRj)+
      xlab("Number of exceedances")+
      theme_bw()+
      COMMON_theme+
      theme(legend.position = "bottom",
            legend.direction = "horizontal")
    GGCorr_evol<-GGCorr_evol+
      geom_vline(aes(xintercept=kstar2,
                     linetype="thresh"))+
      labs(linetype="Legend")+
      scale_color_manual(
        values = c(2,3,4),
        labels=unique(df_forgg$pair_vars)
      )+
      scale_linetype_manual(
        values = c(2,3),
        labels=c("confidence_band",comment_thresh)
      )
    ggsave(filename = paste0(ROOT_export_graph,"Corr/evol_",elt,"_corr_d=",
                             length(l_name),".png"),
           plot=GGCorr_evol,width = 10,height = 5)
    
  }
}
GGCorr_evol
```

```{r}
### Evolution of the raidial vector -------
################

if(Launch_graph_conv){
  ### Convergence for the radius
  #################################
  Evol_Theta_ofRad_criterion<-Extreme_covRad_evol(
    Df_Rad_Orig = Vect_l_function,
    l_name = l_name,
    vector_k = Vector_K2,
    CPU_hearts = coeurs,
    Ref_RiskF = Riskf_data)
  
  Evol_Theta_ofRad_criterion$pair<-sapply(Evol_Theta_ofRad_criterion$pair,
                                          FUN = function(x){
                                            return(Fct_correct_name(x,target = "Surcote",
                                                                    replacement = "Surge"))})
  GGCorr_Radevol<-ggplot(Evol_Theta_ofRad_criterion,
                         aes(x=number_exceed,y=value,
                             col=pair))+
    geom_line()+
    facet_wrap(~pair,scales = "free_y")+
    guides(col="none")+
    labs(linetype="Legend")+
    ylab("Correlation value")+
    xlab("Number of exceedances")+
    geom_vline(aes(xintercept=kstar2,
                   linetype="thresh"))+
    scale_linetype_manual(
      values = c(3),
      labels=c(comment_thresh)
    )+
    theme_bw()+
    COMMON_theme+
    theme(legend.position = "bottom")
    
  GGCorr_Radevol
  ggsave(filename = paste0(ROOT_export_graph,"Corr/evol_criterion_corr_Rad_Thetad=",
                           length(l_name),".png"),
         plot=GGCorr_Radevol,width = 10,height = 5)
  
  par(mfrow=c(1,1))
}

```


```{r}
#### DEPENDS on the choice previously done
OPT_FRECH<-FALSE
par(mfrow=c(1,1))
require(patchwork)
re<-Simul_MV_residuals(result_transformation = Result_MV,
                       l_variables = l_name, Q_thresh = Qfound,
                       list_nb_scores = LIST_NB_SCORES,
                       M = M,rotations_available=Bool_rotations,
                       Params_risk_Function=List_Params_RF
                       ,root_for_export=ROOT_export_graph
                       ,One_PCA_base = ONE_PCA_BASIS,
                       NbScores_Omega = NB_SCORES_OMEGA,
                       f_transf=FTF,f_transf_inv=FTF_inv,
                       opt_Frech = OPT_FRECH,
                       cols_ggplot=cols_)
```

```{r}
### Gaussian Mixture ? 
#####
par(mfrow=c(1,1))
vect_l<-exp(-re$Vect_RiskF_transf^(-1))
vect_lgauss<-apply(vect_l,MARGIN = 2,qnorm)
GM_vectl<-mclust::densityMclust(vect_lgauss,
                                plot=FALSE)
png(filename = paste0(Lg_path,"/mod_GM_bic.png"))
plot(GM_vectl,what="BIC")
dev.off()
##(+) test of gaussian miture vs one component
Vect_l_ID<-scale(vect_lgauss)
Test_GM_vs_1comp<-TwoGM_versus_normal(vect_Id = Vect_l_ID,
                    alpha = 0.05)
Test_GM_vs_1comp
### We do not reject the null hypothesis--> we are
### not in the case of contamination model
n<-1000
d<-2
nu<-rep(1,d)
prob_classes<-c(0.5,0.5)
Result_Cont_Model<-t(replicate(n =n,
                               Simul_Contamination_Model(prob_classes = prob_classes,
                   nu = nu))[1,,])
plot(Result_Cont_Model,
     main="Simulation from contamination model",
     xlab="V1",ylab="V2")
Test_GM_knowingH1<-TwoGM_versus_normal(vect_Id = Result_Cont_Model,alpha = 0.05)

################
Theta_fit<-re$Param_found
Nu<-re$threshold
Vect_RiskF<-sapply(Result_MV$df,unlist)
Vect_RiskF_Frechet_transf<-re$Vect_RiskF_transf

# Symmetric family OR asymmetric family ?  --------------------------------
######################
N<-500
Test_exchangeability<-copula::exchEVTest(x = Vect_RiskF,
                                         estimator = "CFG",
                                          N = N)
print(Test_exchangeability$p.value)
Test_exchangeability_transf<-copula::exchEVTest(x = Vect_RiskF_Frechet_transf,
                                        estimator = "CFG",
                                         N = N)
print(Test_exchangeability$p.value)

### If null hypothesis is rejected, we need to use
### asymmetric models. 

# Testing several copula families for the risk functions----------------------------
#######################
d<-ncol(Vect_RiskF)

```

```{r}
### Analyse Dependence function 
Mod_biv<-list("model"=Name_model)
Estimator<-list()
if(Name_model%in%c("log","hr")){
  Estimator[["dep"]]<-Theta_fit
}
if(Name_model%in%c("ct","bilog")){
  Estimator[["alpha"]]<-Theta_fit[1]
  Estimator[["beta"]]<-Theta_fit[2]
}
Mod_biv[["estimate"]]<-Estimator
```


```{r}

# (Shapes) Correlation between variables OK -------------------------------
######################
First_var<-l_name[1]
Second_var<-l_name[2]
Orig<-Result_MV$orig
ind_var1<-which(names(Orig)==First_var)
ind_var2<-which(names(Orig)==Second_var)
liste_ext<-Create_list_fromALL(l_name = l_name,
                               obj_source = re$obs_exts)
# Correlations Pareto scale -----------------------------------------------
Mat_obs_Pareto<-Fct_correlations(method_corr = "kendall",
                                 df1 =re$obs_exts[[ind_var1]],
                                 df2=re$obs_exts[[ind_var2]])
V1<-re$simul[[ind_var1]]
V2<-re$simul[[ind_var2]]
Mat_simul_Pareto<-Fct_correlations(method_corr = "kendall",
                                   df1 =V1,df2=V2)
summary(Mat_simul_Pareto)
summary(Mat_obs_Pareto)
plot(c(1:37),y = Mat_obs_Pareto,ylim=c(-0.5,0))
lines(c(1:37),y = Mat_simul_Pareto,col="red")
legend(x="topright",legend=c("data","simul"),
       col=c(1,2),lwd=2,bty="n")

# Correlation var1 var2 ---------------------------------------------------
Mat_corr<-Fct_correlations(method_corr = "kendall",
                           df1 =liste_ext[[ind_var2]],
                           df2=liste_ext[[ind_var1]])
Mat_corr_simul<-Fct_correlations(method_corr = "kendall",
                                 df1 =re$simul[[ind_var2]],
                                 df2=re$simul[[ind_var1]])

plot(c(1:37),y = Mat_corr,
     main="Correlations between Hs and S at each time (red in simul)")
lines(c(1:37),y = Mat_corr_simul,
      col="red")




```

```{r}
# Marginal law ------------------------------------------------------------
NB_times<-ncol(re$simul[[ind_var1]])
KS_test_S<-rep(NA,NB_times)
KS_test_HS<-KS_test_S
for(t in c(1:NB_times)){
  KS_test_S[t]<-ks.test(x =re$simul[[ind_var1]][,t],
                        y=liste_ext[[ind_var1]][,t])$p.value
  KS_test_HS[t]<-ks.test(x = re$simul[[ind_var2]][,t],
                         y=liste_ext[[ind_var2]][,t])$p.value
}
plot(KS_test_S)
plot(KS_test_HS)
# Export ------------------------------------------------------------------
##################
for(nameV in l_name){
  write.csv(x =re$simul[[nameV]],
        file=paste0(ROOT_export,nameV,"_",
        CPLMT_graph_theta,"_",METHOD_ANGLE, 
        "_simul",opt_used,".csv"))
  write.csv(x =liste_ext[[nameV]],
          file=paste0(ROOT_export,nameV,"_obs_ext.csv"))
}
```


```{r}

U_sim_frech<-re$Frechet_normal$simul[[l_name[[1]]]]
U_obs_frech<-re$Frechet_normal$obs[[l_name[[1]]]]

Obj_sim<-matrix(NA,nrow = nrow(U_sim_frech),
                ncol = ncol(U_sim_frech)*length(l_name))
Obj_data<-matrix(NA,nrow = nrow(U_obs_frech),
                 ncol = ncol(U_obs_frech)*length(l_name))

Root_sim<-re$Frechet_normal$simul
Root_data<-re$Frechet_normal$obs
List_RiskF<-list()
List_RiskF_data<-list()
Z<-0
for(name in l_name){
  Deb<-Z*ncol(U_sim_frech)+1
  END<-(Z+1)*ncol(U_sim_frech)
  Df_sim<-Root_sim[[Z+1]]
  L2_sim<-apply(Df_sim,MARGIN = 1,FUN = calcul_norm_L2)
  List_RiskF[[name]]<-L2_sim
  Theta_sim<-t(t(Df_sim)%*%diag(L2_sim^(-1)))
  print(summary(Theta_sim))
  Obj_sim[,c(Deb:END)]<-Theta_sim
  rood<-Root_data[[Z+1]]
  colnames(rood)<-c(1:length(names(rood)))
  Df_data<-as.matrix(rood)
  L2_data<-apply(Df_data,MARGIN = 1,FUN = calcul_norm_L2)
  List_RiskF_data[[name]]<-L2_data
  Theta_data<-t(t(Df_data)%*%diag(L2_data^(-1)))
  Obj_data[,c(Deb:END)]<-Theta_data
  Z<-Z+1
  M_shown<-50
  Filename_omega<-paste0(ROOT_export_graph,"Theta/",name,"/",
                         paste0("Omega_sim_vs_obs_",name,".png"))
  Min_y<-min(c(apply(Theta_data,MARGIN = 2,FUN = min),
               apply(Theta_sim,MARGIN = 2,FUN = min)))
  Max_y<-max(c(apply(Theta_data,MARGIN = 2,FUN = max),
               apply(Theta_sim,MARGIN = 2,FUN = max)))
  png(filename =  Filename_omega,width=1400,
      height=500)
  par(mfrow=c(1,2))
  matplot(t(Theta_data[1:M_shown,]),type="l",
          xlab="Index",ylim=c(Min_y,Max_y),
          ylab="value (-)",cex.lab=1.5)
  matplot(t(Theta_sim[1:M_shown,]),type="l",
          ylim=c(Min_y,Max_y),xlab="Index",
          ylab=NA,cex.lab=1.5)
  par(mfrow=c(1,1))
  dev.off()
}


```


```{r}
# ### Riskf
summary(List_RiskF_data[[1]])
summary(List_RiskF[[1]])

z<-1
summary(List_RiskF_data[[z]])
summary(List_RiskF[[z]])
Model<-re$model_EGPD[[l_name[z]]]
Inds_max<-which.max(List_RiskF[[z]])

Vect_max<-c(List_RiskF[[1]][Inds_max],
            List_RiskF[[2]][Inds_max])
Ind_max_data<-which.max(List_RiskF_data[[z]])
plot(List_RiskF_data[[1]],
     List_RiskF_data[[2]],log="xy")
vectcb<-c(List_RiskF_data[[1]][Ind_max_data],
          List_RiskF_data[[2]][Ind_max_data])
points(vectcb[1],vectcb[2],col="red")
points(Vect_max[1],Vect_max[2],col="blue")

plot(List_RiskF[[1]],
     List_RiskF[[2]],log="xy")
points(List_RiskF_data[[1]],
     List_RiskF_data[[2]],log="xy",
     col="red")
### Export Theta for future analysis 
#######
write.csv(file=paste0(ROOT_export,"log=",USE_log,"_Theta_data.csv"),
          x = Obj_data)
write.csv(file=paste0(ROOT_export,"log=",USE_log,"_Theta_sim.csv"),
          x = Obj_sim)

### Work on distrib of Omega
```

```{r}
### RiskF analysis
var_used<-"Surcote"
data_rj<-List_RiskF_data[[var_used]]
sim_rj<-List_RiskF[[var_used]]
print(summary(data_rj))
print(summary(sim_rj))

var_used<-"Hs"
data_rj<-List_RiskF_data[[var_used]]
sim_rj<-List_RiskF[[var_used]]
print(summary(data_rj))
print(summary(sim_rj))

# Evaluate the new expression
list_pairs<-list("1"=c(1,37),
                 "2"=c(1,19),
                 "3"=c(19,56),
                 "4"=c(38,56),
                 "5"=c(56,74))
Summary_pairs_Omega<-sapply(list_pairs,F_automatic_ggplot_marg_Omega,
       Obj_sim=Obj_sim,Obj_data=Obj_data,
       l_name=l_name,cols_ggplot=cols_)
```


```{r}
mu_Theta<-apply(X = Obj_data,MARGIN = 2,FUN = mean)
N_rep<-500
B<-nrow(Obj_data)
N_rep<-500
lq<-c(0.05,0.50,0.95,0.975)
Tend_Theta<-replicate(n =N_rep,expr = Resamples_trends(B = B,
                                                        extremes_indus=Obj_data,list_Q =lq))

Results_data<-sapply(X = lq,FUN = function(x,q){
  return(apply(x,MARGIN = 2,FUN =function(x){return(quantile(x,q))}))},
                     x=Obj_data)
Results_sim<-sapply(X = lq,FUN = function(x,q){
  return(apply(x,MARGIN = 2,FUN =function(x){return(quantile(x,q))}))},
                    x=Obj_sim)

bound_minus05<-apply(Tend_Theta[1,,],MARGIN = 1,
                     FUN = function(x){return(quantile(x,0.025))})
bound_plus05<-apply(Tend_Theta[1,,],MARGIN = 1,
                    FUN = function(x){return(quantile(x,0.975))})

##########
bound_minus50<-apply(Tend_Theta[2,,],MARGIN = 1,
                     FUN = function(x){return(quantile(x,0.025))})
bound_plus50<-apply(Tend_Theta[2,,],MARGIN = 1,
                    FUN = function(x){return(quantile(x,0.975))})

########
bound_minus95<-apply(Tend_Theta[3,,],MARGIN = 1,
                     FUN = function(x){return(quantile(x,0.025))})
bound_plus95<-apply(Tend_Theta[3,,],MARGIN = 1,
                    FUN = function(x){return(quantile(x,0.975))})

######
bound_minus975<-apply(Tend_Theta[4,,],MARGIN = 1,
                      FUN = function(x){return(quantile(x,0.025))})
bound_plus975<-apply(Tend_Theta[4,,],MARGIN = 1,
                     FUN = function(x){return(quantile(x,0.975))})
matplot(t(re$simul[[l_name[1]]]),type="l")
L2_s<-apply(X = re$simul[[l_name[1]]],MARGIN = 1,FUN = calcul_norm_L2)
L2_U<-apply(X = re$simul[[l_name[2]]],MARGIN = 1,FUN = calcul_norm_L2)

```


```{r}
# Graphics ----------------------------------------------------------------

df<-cbind.data.frame(c(Results_data),
                     c(bound_minus05,bound_minus50,
                       bound_minus95,bound_minus975),
                     c(bound_plus05,bound_plus50,
                       bound_plus95,bound_plus975))
colnames(df)<-c("estimator","bound_minus","bound_plus")

df$estimator_simul<-c(Results_sim)
df$Time<-rep(c(1:ncol(Obj_data)),4)
df$percent<-c(rep("Q05",ncol(Obj_data)),
              rep("Q50",ncol(Obj_data)),
              rep("Q95",ncol(Obj_data)), 
              rep("Q975",ncol(Obj_data)))
df$Time
First<-which(df$Time<=37)
df_first<-df[First,]
GG_percent<-ggplot(data=df_first,aes(x=Time,y=estimator,group=interaction(percent),col="data"))+
  facet_wrap(~percent,scales="free_y")+
  geom_line()+
  geom_point()+
  geom_ribbon(mapping = aes(ymin=bound_minus,ymax=bound_plus,col="confidence_band"),alpha=0.15,
              fill="grey", linetype = "dashed")+
  geom_line(aes(x=Time,y=estimator_simul,col="simulations"),linetype=2)+
  theme(axis.title=element_text(size=25),
        legend.text=element_text(size=14),
        legend.title = element_text(size=15),
        axis.text = element_text(size=12),
        strip.text = element_text(size = 12))+
  scale_color_manual(values=cols_)+
  xlab("Time")+
  labs(col="Legend")
ggsave(plot = GG_percent,
       filename = paste0(Theta_path,"/",l_name[1],"/",
                    CPLMT_graph_theta,"_",METHOD_ANGLE,
                         "_Percent_theta_",l_name[1],
                         ".png"),
       width=8,height = 6)

Second<-which(df$Time>37)
df_second<-df[Second,]
GG_percent<-ggplot(data=df_second,aes(x=Time,y=estimator,group=interaction(percent),col="data"))+
  facet_wrap(~percent,scales="free_y")+
  geom_line()+
  geom_point()+
  geom_ribbon(mapping = aes(ymin=bound_minus,ymax=bound_plus,col="confidence_band"),alpha=0.15,
              fill="grey", linetype = "dashed")+
  geom_line(aes(x=Time,y=estimator_simul,col="simulations"),linetype=2)+
  theme(axis.title=element_text(size=25),
        legend.text=element_text(size=14),
        legend.title = element_text(size=15),
        axis.text = element_text(size=12),
        strip.text = element_text(size = 12))+
  scale_color_manual(values=cols_)+
  xlab("Time")+
  labs(col="Legend")
ggsave(plot = GG_percent,
       filename =paste0(Theta_path,"/",l_name[2],"/",CPLMT_graph_theta,"_",
                        METHOD_ANGLE,"_Percent_theta_",l_name[2],
                        ".png"),width=8,height = 6)
j_coord<-1
j_nl2<-1
pval_indep<-cor.test(re$coords_data[,j_coord],
                     y = Vect_l_function[re$Indices_exts,j_nl2],
                     method = "kendall")$p.value
pval_indep
Sub<-cbind(re$coords_data[,1],re$coords_data[,2])
UNifs<-VineCopula::pobs(Sub)

plot(UNifs[,1],UNifs[,2])

Result<-lm(UNifs[,2]~UNifs[,1]+I(UNifs[,1]^2))
png("test.png")
plot(UNifs[,1],UNifs[,2])
points(UNifs[,1],Result$fitted.values,col="red")
dev.off()


```


```{r}
# Theta_found vs cost evolution ---------------------------------
######
model_used<-List_Params_RF[["name_model"]]
theta<-re$Param_found
if(Approach=="AD"){
  if(model_used%in%c("log","hr")){
    V_11<-2*evd::abvevd(x = (1/2),dep =theta,
                        model =model_used)
  }
  if(model_used%in%c("ct","bilog")){
    V_11<-2*evd::abvevd(x = (1/2),alpha = theta[1],
                        beta = theta[2],
                        model =model_used)
  }
  
  Chi_estim<-2-V_11
  print(paste0("The Chi would be around ", round(Chi_estim,2)))
  png(paste0(Lg_path,"/",model_used,"_model_param_vs_data.png"),
      height=800,width = 1000)
  par(mfrow=c(1,2))
  POT::chimeas(data = Result_MV$df,ask = FALSE,which = 1)
  abline(h=Chi_estim,col="red")
  abline(h=0,col="black")
  POT::chimeas(data = Result_MV$df,ask = FALSE,which = 2)
  par(mfrow=c(1,1))
  dev.off()
  
  if(List_Params_RF[["name_RF"]]!="max"){
    Excedents_lprime<-Vect_l_function[re$Indices_exts,]
    Evol_cost<-function(theta_candidate){
      Objective_function(theta = theta_candidate,
                         weightFun = List_Params_RF[["weightFunction"]],
                         dWeightFun = List_Params_RF[["dWeightFunction"]],
                         Extreme_inds =as.list(as.data.frame(t(Excedents_lprime))) ,
                         u = re$threshold,
                         model_used = List_Params_RF[["name_model"]])
      
    }
    vect_candidates<-seq.int(from = 0.6,to = 0.99,length.out = 20 )
    Cost_evol<-sapply(vect_candidates,
                      Evol_cost)
    # Export evolution alpha --------------------------------------------------
    png(file = paste0(ROOT_export,"evol_alpha_param.png"),
        bg = "transparent")
    plot(vect_candidates,Cost_evol,xlab="Param",ylab="Cost")
    dev.off()
  }
}



```

```{r}
# Summary of the results --------------------------------------------------
Riskmv<-re$Risk_MV
Inds_exts<-re$Indices_exts
### if you use EXTGPD, you must only take pos values-->
Inds_exts<-Inds_dates_pos[Inds_exts]
DF_inds_risk<-cbind.data.frame(Riskmv,
                               Inds_exts)
colnames(DF_inds_risk)<-c("RiskF","indexes")
#Export dates of extreme events ------------------------------------------
write.csv(file=paste0(ROOT_export,"ext_series_chosen_risks.csv"),
          x = DF_inds_risk)

L_extremes<-Vect_l_function[re$Indices_exts,]

```


```{r}

# Kokozka -----------------------------------------------------------------
# #######

### Consistency results
source("functions_MV/Fonctions_consistency.R")
K<-length(re$Indices_exts)
Extreme_cov_data<-Launch_extreme_cov_per_K(
  liste_MV_Orig = ALL_transf,
  l_name =l_name,
  k = K,
  vect_lg = Riskf_data)
Nboot<-500
Bootstrap_all_results<-t(replicate(n = Nboot,
    Estimator_1boostrap_sample(list_obs_exts = re$Frechet_normal$obs,
                            l_name = l_name,Thresh_lg = re$threshold)))
Alpha_param<-0.05

###Mean stat
M_stat<-apply(X =Bootstrap_all_results,MARGIN = 2,
              FUN = unlist)

Bounds_data<-apply(X = M_stat,FUN=F_bounds_per_column,
            MARGIN = 2,Alpha_q=Alpha_param)
Extreme_cov_simul<-Estimator_rho_sig_knowing_K(indexes_used = c(1:N),
                            l_name = l_name,L = 37,
                            list_obs_exts = re$Frechet_normal$simul,
                            d = 2,Thresh_lg = re$threshold)
Bootstrap_all_results_simul<-t(replicate(n = Nboot,
           Estimator_1boostrap_sample(
                   list_obs_exts = re$Frechet_normal$simul,
                   l_name = l_name,
                   Thresh_lg = re$threshold) ))
M_stat_simul<-apply(X =Bootstrap_all_results_simul,MARGIN = 2,
              FUN = unlist)
Bounds_simul<-apply(X = M_stat_simul,FUN=F_bounds_per_column,
                   MARGIN = 2,Alpha_q=Alpha_param)
df_comb<-rbind.data.frame(as.matrix(M_stat),
                      as.matrix(M_stat_simul))
head(df_comb)
colnames(df_comb)<-c("V1","V2")
df_comb$origin<-c(rep("data",nrow(M_stat)),
              rep("simulations",nrow(M_stat_simul)))

GG_sig<-ggplot(data = df_comb)+
  geom_density(aes(x=V1,fill=origin),
               alpha=0.6)+
  xlab("Statistic")+
  ylab(expression(sigma[XY]~"density"))+
  scale_fill_manual(values=cols_)+
  theme(axis.title = element_text(size=20),
        axis.text = element_text(size=15),
        legend.text = element_text(size=14),
        legend.title = element_text(size=13))+
  labs(fill="Legend")
ggsave(filename = paste0(ROOT_export_graph,
                         l_name[1],"_",
                         l_name[2],"_sig_distribs.png"),
       width=8,height=6,plot =GG_sig)
GG_rho<-ggplot(data = df_comb)+
  geom_density(aes(x=V2,fill=origin),
               alpha=0.6)+
  xlab("Statistic")+
  ylab(expression(rho[XY]~"density"))+
  scale_fill_manual(values=cols_)+
  theme(axis.title = element_text(size=20),
        axis.text = element_text(size=15),
        legend.text = element_text(size=14),
        legend.title = element_text(size=13))+
  labs(fill="Legend")
ggsave(filename = paste0(ROOT_export_graph,
         l_name[1],"_",
         l_name[2],"_rho_distribs.png"),
       width=8,height=6,plot =GG_rho)

Maxi<-apply(X = Result_MV$df,MARGIN = 1,FUN = max)
inds_exts<-which(Maxi>re$threshold)
z<-1
marg_z<-Result_MV$df[inds_exts,z]



```

```{r}
# Shapes and coordinates --------------------------------------------------
par(mfrow=c(1,2))
#ind_var1

if(ONE_PCA_BASIS==FALSE){
  MAX_Eigen<-max(re$EIGEN_functions[[ind_var1]])
  MIN_Eigen<-min(re$EIGEN_functions[[ind_var1]])
  plot(c(1:37),re$EIGEN_functions[[ind_var1]][,1],ylim=c(MIN_Eigen,MAX_Eigen),
       ylab=expression(nu[j]),xlab="Time")
  lines(c(1:37),re$EIGEN_functions[[ind_var1]][,2],col="green")
  lines(c(1:37),re$EIGEN_functions[[ind_var1]][,3],col="red")
  
  MAX_Eigen<-max(re$EIGEN_functions[[ind_var2]])
  MIN_Eigen<-min(re$EIGEN_functions[[ind_var2]])
  plot(c(1:37),re$EIGEN_functions[[ind_var2]][,1],ylim=c(MIN_Eigen,MAX_Eigen),
       ylab=expression(nu[j]),xlab="Time")
  lines(c(1:37),re$EIGEN_functions[[ind_var2]][,2],col="green")
  mtext("PCA eigen functions for the variables",outer=TRUE,
        line=-2)
  
}else{
  MAX_Eigen<-max(re$EIGEN_functions)
  MIN_Eigen<-min(re$EIGEN_functions)
  plot(c(1:37),re$EIGEN_functions[c(1:37),1],ylim=c(MIN_Eigen,MAX_Eigen),
       ylab=expression(nu[j]),xlab="Time")
  lines(c(1:37),re$EIGEN_functions[c(1:37),2],col="green")
  lines(c(1:37),re$EIGEN_functions[c(1:37),3],col="red")
  
  plot(c(1:37),re$EIGEN_functions[c(38:74),1],ylim=c(MIN_Eigen,MAX_Eigen),
       ylab=expression(nu[j]),xlab="Time")
  lines(c(1:37),re$EIGEN_functions[c(38:74),2],col="green")
  lines(c(1:37),re$EIGEN_functions[c(1:37),3],col="red")
}
png(filename = paste0(Theta_path,"/corrs_BW_coords_sim_data.png"),
    height=800,width=1000)
par(mfrow=c(1,2))
corrplot::corrplot(cor(re$coords_data))
corrplot::corrplot(cor(re$coords_simul))
par(mfrow=c(1,1))
dev.off()
j<-5
plot(density(re$coords_data[,j]))
plot(density(re$coords_simul[,j]))
par(mfrow=c(1,1))

# Coords ------------------------------------------------------------------
NDIM<-ncol(re$coords_simul)
KS_results_coords<-rep(NA,NDIM)
for(j in c(1:NDIM)){
  KS_results_coords[j]<-ks.test(re$coords_simul[,j],
                                re$coords_data[,j])$p.value
}
write.csv(file = paste0(ROOT_export,CPLMT_graph_theta,"_",METHOD_ANGLE,"_coord_data.csv"),
          x = re$coords_data)
write.csv(file = paste0(ROOT_export,CPLMT_graph_theta,"_",METHOD_ANGLE,"_coord_simul.csv"),
          x = re$coords_simul)
KS_results_coords
# Illustration ------------------------------------------------------------
Simul<-re$simul

N_shown<-10
Int_conf<-function(df,Q,df_simul){
  int_1<-apply(X = df,MARGIN=2,FUN = function(x){
    return(quantile(x,Q))
  })
  int_2<-apply(X = df_simul,MARGIN=2,FUN = function(x){
    return(quantile(x,Q))
  })
  return(list("obs"=int_1,
              "simul"=int_2))
}
Int_surge<-Int_conf(df = Simul[[ind_var1]],
                    Q = 0.025,df_simul = re$obs_exts[[ind_var1]])
Int_surge2<-Int_conf(df = Simul[[ind_var1]],
                     Q = 0.975,df_simul = re$obs_exts[[ind_var1]])
Int_Hs<-Int_conf(df = Simul[[ind_var2]],
                 Q = 0.025,df_simul = re$obs_exts[[ind_var2]])
Int_Hs2<-Int_conf(df = Simul[[ind_var2]],
                  Q = 0.975,df_simul = re$obs_exts[[ind_var2]])
DF_first<-rbind.data.frame(Simul[[ind_var1]],
                           re$obs_exts[[ind_var1]])

Indexes_data<-sample(c(1:nrow(Simul[[ind_var1]])),size = N_shown,
                     replace=FALSE)
Indexes_sim<-sample(c(1:nrow(re$obs_exts[[ind_var1]])),size = N_shown,
                    replace=FALSE)

Source<-c(rep("simul",nrow(Simul[[ind_var1]])),
          rep("data",length(re$Indices_exts)))
DF_first$source<-Source
DF_second<-rbind.data.frame(Simul[[ind_var2]],re$obs_exts[[ind_var2]])
DF_second$source<-Source

Melteur_first<-melt(DF_first)
L<-table(Melteur_first$variable)[1]
Melteur_first$index<-as.character(rep(c(1:L),nrow(Melteur_first)/L))
Melteur_first$variable<-as.numeric(Melteur_first$variable)
colnames(Melteur_first)<-c("origin","Time",
                           "value","index")
Melteur_first$ymin<-ifelse(Melteur_first$origin=="simul",
                           Int_surge$simul[Melteur_first$Time],
                           Int_surge$obs[Melteur_first$Time])
Melteur_first$ymax<-ifelse(Melteur_first$origin=="simul",
                           Int_surge2$simul[Melteur_first$Time],
                           Int_surge2$obs[Melteur_first$Time])
Melteur_second<-melt(DF_second)

L<-table(Melteur_second$variable)[1]
Melteur_second$index<-as.character(rep(c(1:L),nrow(Melteur_second)/L))
Melteur_second$variable<-as.numeric(Melteur_second$variable)
colnames(Melteur_second)<-c("origin","Time",
                            "value","index")
Melteur_second$ymin<-ifelse(Melteur_second$origin=="simul",
                            Int_Hs$simul[Melteur_first$Time],
                            Int_Hs$obs[Melteur_first$Time])
Melteur_second$ymax<-ifelse(Melteur_second$origin=="simul",
                            Int_Hs2$simul[Melteur_first$Time],
                            Int_Hs2$obs[Melteur_first$Time])

Melteur_all<-rbind.data.frame(Melteur_first,Melteur_second)
Melteur_all$functional<-c(rep(l_name[1],nrow(Melteur_first)),
                          rep(l_name[2],nrow(Melteur_second)))


D_<-which(Melteur_all$origin=="data")
Ind_used_data<-sample(Melteur_all[D_,]$index,size = N_shown,
                      replace = FALSE)
Ind_used_sim<-sample(Melteur_all[-D_,]$index,size = N_shown,
                     replace = FALSE)

cond_data<-Melteur_all$index%in%union(Ind_used_sim,
                                      Ind_used_data)
Melteur_all$Time<-(Melteur_all$Time-19)/6
Melteur_all$index<-as.numeric(Melteur_all$index)
EXPLES_simul<-ggplot(Melteur_all[cond_data,],aes(x=Time,y=value,col=index,
                                                 group=interaction(index)))+
  guides(col="none")+
  facet_wrap(~functional+origin)+
  geom_line()+
  scale_color_continuous(type="viridis")
EXPLES_simul
ggsave(filename=paste0(TEND_path,"/exples_simul_MV.png"),
       plot = EXPLES_simul,width = 6,height = 6)

Mlt_copy<-Melteur_all
Mlt_copy$Time<-as.character(Mlt_copy$Time)

```

```{r}
# Violin plot -------------------------------------------------------------
############
Mlt_copy$Time<-as.character(Mlt_copy$Time)
DISTRIB_marginals_plot<-ggplot(Mlt_copy,aes(y=value,x=Time,fill=functional))+
  geom_boxplot(alpha=0.2,width=0.1)+
  geom_violin()+
  xlab(" ")+
  facet_wrap(~functional+origin,scales="free_y")+
  labs(fill="Legend")+
  theme(axis.text.x = element_blank())

ggsave(filename=paste0(ROOT_export_graph,"Tend/",CPLMT_graph_theta,"_",METHOD_ANGLE,"_violin_plot.png"),
       plot = DISTRIB_marginals_plot,width = 6,
       height = 6)

par(mfrow=c(1,1))
Pareto_S<-Result_MV$resume[[ind_var1]]$transf
Pareto_Hs<-Result_MV$resume[[ind_var2]]$transf
L2_P_S<-apply(Pareto_S[re$Indices_exts,],MARGIN = 1,FUN = calcul_norm_L2)
L2_P_HS<-apply(Pareto_Hs[re$Indices_exts,],MARGIN = 1,FUN = calcul_norm_L2)
ks.test(L2_P_HS,L2_P_S)
wilcox.test(L2_P_HS,L2_P_S)

L2_pto_sur<-apply(re$Frechet_normal$simul[[ind_var1]],MARGIN = 1,
                  FUN = calcul_norm_L2)
L2_pto_Hs<-apply(re$Frechet_normal$simul[[ind_var2]],MARGIN = 1,
                 FUN = calcul_norm_L2)
DF_data_vectL<-matrix(NA,ncol=length(names(re$Frechet_normal$simul)),
                      nrow =length(re$Indices_exts))
for(j in c(1:length(l_name))){
  name_j<-names(Result_MV$resume)[j]
  PTO_j<-Result_MV$resume[[name_j]]$transf
  Output_j<-apply( PTO_j[re$Indices_exts,],MARGIN = 1,
                   FUN = calcul_norm_L2)
  DF_data_vectL[,j]<-Output_j
}

Min_x<-min(min(L2_pto_sur),min(L2_P_S))
Max_x<-max(max(L2_pto_sur),max(L2_P_S))

Min_y<-min(min(L2_pto_Hs),min(L2_P_HS))
Max_y<-max(max(L2_pto_Hs),max(L2_P_HS))
X_name<-ifelse(l_name[1]=="Surcote",yes = "Surge",no=l_name[1])
Y_name<-ifelse(l_name[2]=="Surcote",yes = "Surge",no=l_name[2])
par(mfrow=c(1,1))
png(filename = paste0(Lg_path,"/pair_Lg.png"))

plot(L2_P_S,L2_P_HS,log = 'xy',
     xlab=paste0("Z(",X_name,") "),
     ylab=paste0("Z(",Y_name,") "),
     ylim = c(Min_y,Max_y),
     xlim=c(Min_x,Max_x))
points(L2_pto_sur,
       L2_pto_Hs,col="red",cex=0.5)
if(!Name_riskF%in%c("Weighted_NQ","max","min")){
  ## Change the threshold used.
  J_plot<-2
  X_private<-DF_data_vectL[,-J_plot]
  x_bound<-seq.int(from = 0.001,to =20,length.out =100)
  y_bound<-sapply(x_bound,FUN=Shape_boundary,
                  j = J_plot,ul = re$threshold,RiskF = Risk_f)
  lines(x_bound,y_bound,col="blue")
}else{
  abline(h=re$threshold,v=re$threshold,col="blue")
}
dev.off()
```


```{r}


## originally
Min_x2<-min(min(Vect_l_function[,1]),min(L2_pto_sur))
Max_x2<-max(max(Vect_l_function[,1]),max(L2_pto_sur))

Min_y2<-min(min(Vect_l_function[,2]),min(L2_pto_Hs))
Max_y2<-max(max(Vect_l_function[,2]),max(L2_pto_Hs))
plot(Vect_l_function,xlim=c(Min_x2,Max_x2),
     ylim=c(Min_y2,Max_y2),log="xy")

# DATES<-read.csv(file = "../ss_tend/HIVER/dates_prises.csv")[,2]
# 
# Inds_2008<-which(DATES=="10/03/2008")
# Dates_storm<-c("10/03/2008","28/02/2010","10/02/2009",
#                "27/10/2004","07/02/2001","10/01/2001")
# Cplmt_dates_1<-c("26/02/2010","08/03/2008","08/02/2009",
#                  "25/10/2004","05/02/2001","08/01/2001")
# 
# Cplmt_dates_2<-c("09/03/2008","27/02/2010","09/02/2009",
#                  "26/10/2004","06/02/2001","09/01/2001")
# Inds_storm<-union(which(substr(DATES,1,10)%in%Dates_storm),
#                   which(substr(DATES,1,10)%in%Cplmt_dates_1)
# ) 
# Inds_storm<-union(Inds_storm,
#                   which(substr(DATES,1,10)%in%Cplmt_dates_2)
# )
# DATES[Inds_storm]
# ind_Joh<-which(substr(DATES,1,10)=="10/03/2008")
# DATA_pos_neg<-read.csv(file = paste0(l_root,l_name[1],"_residuals.csv"))[,c(2:38)]
# DATA_pos_neg[ind_Joh,]
# ind_storm_found<-intersect(Inds_storm,
#                            Result_MV$SUB_set)
# Storms_seen<-DATES[ind_storm_found]
# F_return_index<-function(x){
#   return(Result_MV$SUB_set[x])
# }
# Index_storm<-which( Result_MV$SUB_set%in%ind_storm_found)
# Correspondg_vectors<-Vect_l_function[Index_storm,]
# df_sim<-cbind.data.frame(L2_pto_sur,L2_pto_Hs)
# colnames(df_sim)<-sapply(c(1:length(l_name)),
#                          FUN=function(x){
#                            return(paste0("V",x))
#                          })
# VECT2<-Vect_l_function
# colnames(VECT2)<-colnames(df_sim)
# Correspondg_vectors
# X_storms<-Correspondg_vectors[,1]
# Y_storms<-Correspondg_vectors[,2]
# ANOTATE_data<-data.frame(x=X_storms,y=Y_storms,
#                          label=rep("storm",length(Index_storm)))
# 
# GG_data_and_exceed<-ggplot(data=VECT2,aes(x=V1,y=V2))+
#   geom_point()+
#   geom_point(data = ANOTATE_data, 
#              aes(x, y,col="storm"), size = 4,
#              shape=0) +
#   annotate("text", x = (X_storms)*(8/10), y = Y_storms*(9/10), 
#            label=Storms_seen,colour = "red", 
#            size = 5)+
#   scale_y_continuous(transform="log",
#                      labels = label_number(accuracy = 0.1))+
#   scale_x_continuous(transform="log",
#                      labels = label_number(accuracy = 0.1))+
#   theme(axis.title=element_text(size=15),
#         legend.text=element_text(size=14),
#         legend.title = element_text(size=15),
#         axis.text = element_text(size=14))+
#   geom_hline(aes(yintercept = re$threshold,col="exceedances"),
#              linetype="dashed")+
#   geom_vline(aes(xintercept=re$threshold,col="exceedances"),
#              linetype="dashed")+
#   scale_color_manual(values=c("exceedances"="red",
#                               "storm"="black"))+
#   labs(col="Legend")+
#   xlab(paste0("Norm of T(",l_name[1],") (.)"))+
#   ylab(paste0("Norm of T(",l_name[2],") (.)"))
# 
# ggsave(plot = GG_data_and_exceed,
#        filename = paste0(Lg_path,"/norm_ext",opt_used,".png"),
#        width = 8,height = 8)
# DF_sim_vs_obs<-rbind.data.frame(VECT2,df_sim)
# DF_sim_vs_obs$origin<-c(rep("data",nrow(VECT2)),
#                         rep("simulations",nrow(df_sim)))
# 
# GG_repre_exts_norms<-ggplot(data=DF_sim_vs_obs,aes(x=V1,y=V2))+
#   geom_point(aes(col=origin,size=origin))+
#   geom_point(data = ANOTATE_data, 
#              aes(x, y,col=label),size=4,shape=0) +
#   annotate("text", x = (X_storms)*(8/10), y = Y_storms*(9/10), 
#            label=Storms_seen,colour = "red", 
#            size = 5)+
#   scale_y_continuous(transform="log",
#                      labels = label_number(accuracy = 0.1))+
#   scale_x_continuous(transform="log",
#                      labels = label_number(accuracy = 0.1))+
#   theme(axis.title=element_text(size=15),
#         legend.text=element_text(size=14),
#         legend.title = element_text(size=15),
#         axis.text = element_text(size=14))+
#   geom_hline(aes(yintercept = re$threshold,col="exceedances"),
#              linetype="dashed",)+
#   geom_vline(aes(xintercept=re$threshold,col="exceedances"),
#              linetype="dashed")+
#   scale_color_manual(values=c("data"="blue",
#                               "simulations"="orange",
#                               "storm"="black",
#                               "exceedances"="red"))+
#   scale_size_manual(values=c("data"=2,
#                              "simulations"=1))+
#   labs(col="Legend")+
#   guides(size="none")+
#   xlab(paste0("Norm of T(",l_name[1],") (.)"))+
#   ylab(paste0("Norm T(",l_name[2],") (.)"))
# 
# ggsave(plot = GG_repre_exts_norms,
#        filename = paste0(Lg_path,"/ext_simuls_RM",opt_used
#                          ,".png"),
#        width = 8,height = 8)
cor(L2_P_S,L2_P_HS,method = "kendall")
cor(L2_pto_sur,L2_pto_Hs
    ,method = "kendall")
POT::chimeas(cbind(L2_pto_Hs,L2_pto_sur),ask=FALSE)

Maximum<-apply(cbind(L2_pto_Hs,L2_pto_sur),MARGIN = 1,FUN = max)
summary(Maximum)

Maximum_obs<-apply(cbind(L2_P_S,L2_P_HS),MARGIN = 1,FUN = max)
summary(Maximum_obs)

fUl<-min(apply(cbind(L2_P_HS,L2_P_S),MARGIN = 1,FUN = max))
cor(L2_P_HS,L2_P_S,method = "kendall")
cor(L2_pto_Hs,L2_pto_sur,method = "kendall")

```

```{r}

# PCA for the angle -------------------------------------------------------
val_chosen<-c(3,2)
NPCA<-as.list(val_chosen)


#Calculate correlations --------------------------------------------------
#Shape correlation var1 var2 ---------------------------------------------
Mat_obs<-Fct_correlations(method_corr = "kendall",
                          df1 =Obj_data[,c(1:37)],
                          df2=Obj_data[,c(38:74)])
apply(Obj_data[,c(1:37)],MARGIN = 2,FUN = sd)
apply(Obj_sim[,c(1:37)],MARGIN = 2,FUN = sd)
Conf_interval_angle<-Conf_interval_correlations_2V(df1 = Obj_data[,c(1:37)],
                                                   df2 = Obj_data[,c(38:74)],
                                                   niv_conf = 0.05,
                                                   method_corr = "kendall",
                                                   NB_boot = 500)
Mat_simul<-Fct_correlations(method_corr = "kendall",
                            df1 =Obj_sim[,c(1:37)],
                            df2=Obj_sim[,c(38:74)])
Data_corr<-as.data.frame(Conf_interval_angle)
colnames(Data_corr)<-c("bound_inf","data","bound_sup")
Data_corr$simulations<-Mat_simul
Data_corr$Time<-(c(1:nrow(Data_corr))-19)/6
GG_corr_shape<-ggplot(data=Data_corr,aes(x=Time,y=data,col="data"))+
  geom_ribbon(aes(ymin=bound_inf,col="confidence_band",
                  ymax=bound_sup),alpha=0.05,fill="grey",
              linetype="dashed")+
  geom_line(aes(y=simulations,col="simulations"))+
  geom_line()+
  geom_point()+
  xlab("Time (hour) with respect to tidal peak")+
  scale_color_manual(values = cols_)+
  ylab("correlation coefficient")+
  labs(col="Legend")+theme(axis.title=element_text(size=15),
                           legend.text=element_text(size=10))
ggsave(filename = paste0(ROOT_export_graph,CPLMT_graph_theta,"_",METHOD_ANGLE,"_corr_shape",opt_used
                         ,".png"),
       plot = GG_corr_shape,width=6,height = 6)


```

```{r}
#End of the code ----------------------------------------------------------------
###################
stopCluster(coeurs)
```

